import type { LangCode } from '@/lib/lang-store'
import { localizeBrandValue } from '@/lib/brand'
import { ACTIVE_LANGUAGES } from '@/lib/quiz-config'

export type Copy = {
  plans: { name: string; desc: string; badge: string | null }[]
  pageTitle: string
  pageSub: string
  stickyTimerLabel: string
  stickyMinutesLabel: string
  stickySecondsLabel: string
  beforeLabel: string
  afterLabel: string
  bodyFatLabel: string
  bodyFatHigh: string
  bodyFatNormal: string
  bodyFatLow: string
  fitnessLevelLabel: string
  fitnessLevelBeginner: string
  fitnessLevelIntermediate: string
  fitnessLevelAdvanced: string
  discount: (v: string) => string
  perDay: (v: string) => string
  moneyBackRow: string
  cta: string
  consentPrefix: string
  terms: string
  privacy: string
  refund: string
  consentAnd: string
  consentError: string
  consentBody: (today: string, renew: string) => string
  yourResults: string
  primaryGoal: string
  fitnessLevel: string
  sleepQuality: string
  fitnessAge: string
  fitnessAgeValue: (years: number) => string
  workoutTitle: string
  workoutBadge: string
  waterTitle: string
  waterBadge: string
  readyHeading: string
  bulletTitle: string
  bullets: string[]
  whatYouGet: string
  features: { title: string; desc: string }[]
  phoneMealTag: string
  phoneMealTitle: string
  phoneMealMeta: string
  phoneIngredientsTab: string
  phoneNutritionTab: string
  phoneIngredient1: string
  phoneIngredient1Qty: string
  phoneIngredient2: string
  phoneIngredient2Qty: string
  phoneIngredient3: string
  phoneIngredient3Qty: string
  phoneIngredient4: string
  phoneIngredient4Qty: string
  socialText: string
  socialSub: string
  socialCta: string
  ratingsHeadline: string
  ratingsSubline: string
  ratingsAppStore: string
  ratingsPlayStore: string
  ratingsQuote: string
  ratingsQuoteSource: string
  storiesHeading: string
  storiesSubheading: string
  verifiedCustomer: string
  choosePlanAria: string
  savingsText: string
  trustSecureCheckout: string
  trustCancelAnytime: string
  trustInstantAccess: string
  footerLanguageLabel: string
  secretGiftPill: string
  secretGiftLead: string
  secretGiftTitle: string
  secretGiftBody: string
  giftSectionTitle: string
  giftSectionHighlight: string
  giftSectionWorth: string
  giftSectionBody: string
  guaranteeLinkLabel: string
  guaranteePrefix: string
  personalHeading: (name: string) => string
  guaranteeTitle: string
  guaranteeBody: string
  footer: string
  goalLabels: Record<string, string>
  sleepLabels: Record<string, string>
  fitnessLabels: Record<string, string>
  bmi: Record<'Normal' | 'Underweight' | 'Overweight' | 'Obese', { title: string; text: (bmi: string) => string }>
}

export const EN: Copy = {
  plans: [
    { name: "7-day plan", desc: "USD 1.09 / day", badge: null },
    { name: "1-month plan", desc: "USD 0.61 / day", badge: "Most popular — save over 50%" },
    { name: "3-month plan", desc: "USD 0.31 / day", badge: "Best value" }
  ],
  pageTitle: "Your Personalized Zero Carbs Challenge plan is ready",
  pageSub: "Pick the plan that fits you best.",
  stickyTimerLabel: "Your special 50%+ discount is reserved for:",
  stickyMinutesLabel: "minutes",
  stickySecondsLabel: "seconds",
  beforeLabel: "Now",
  afterLabel: "Goal",
  bodyFatLabel: "Body fat",
  bodyFatHigh: "High",
  bodyFatNormal: "Normal",
  bodyFatLow: "Low",
  fitnessLevelLabel: "Fitness level",
  fitnessLevelBeginner: "Beginner",
  fitnessLevelIntermediate: "Intermediate",
  fitnessLevelAdvanced: "Advanced",
  discount: (v) => "with __V__ discount".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ per day".replace("__V__", String(v)),
  moneyBackRow: "30-day money-back guarantee — Try it with no risk. If it is not right for you, you can get your money back.",
  cta: "Get my plan",
  consentPrefix: "By continuing, you agree to our",
  terms: "Terms of Use",
  privacy: "Privacy Policy",
  refund: "Refund Policy",
  consentAnd: "and",
  consentError: "Please accept the terms to continue.",
  consentBody: (today, renew) => "This is a subscription that renews automatically. You will be charged __TODAY__ today. After the plan period ends, your plan will renew at __RENEW__, unless you cancel. You can cancel anytime at least 48 hours before renewal by contacting support email:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Your results",
  primaryGoal: "PRIMARY GOAL",
  fitnessLevel: "FITNESS LEVEL",
  sleepQuality: "SLEEP QUALITY",
  fitnessAge: "FITNESS AGE",
  fitnessAgeValue: (years) => "__YEARS__ years older than your actual age".replace("__YEARS__", String(years)),
  workoutTitle: "Your personalized Zero Carbs Challenge plan",
  workoutBadge: "RECOMMENDED WORKOUT DURATION",
  waterTitle: "Water Intake",
  waterBadge: "RECOMMENDED DAILY WATER INTAKE",
  readyHeading: "Your plan with Zero Carbs Challenge is ready!",
  bulletTitle: "With Zero Carbs Challenge, you can:",
  bullets: ["Build confidence", "Boost your energy", "Reduce stress", "Support your body over time"],
  whatYouGet: "What you get with Zero Carbs Challenge",
  phoneMealTag: "Breakfast",
  phoneMealTitle: "Fried Salmon with Green Beans",
  phoneMealMeta: "4.8 · 10 min · 498 kcal",
  phoneIngredientsTab: "Ingredients",
  phoneNutritionTab: "Nutrition",
  phoneIngredient1: "Green Beans",
  phoneIngredient1Qty: "1 cup",
  phoneIngredient2: "Lemon",
  phoneIngredient2Qty: "1 medium",
  phoneIngredient3: "Sesame Seeds",
  phoneIngredient3Qty: "1 tbsp",
  phoneIngredient4: "Olive Oil",
  phoneIngredient4Qty: "3 1/2 tsp",
  features: [
    { title: "A personalized plan", desc: "Your plan is built around your body, your energy, and your daily life — not a generic routine." },
    { title: "Simple daily direction", desc: "You always know what to do today, without thinking or planning." },
    { title: "Adaptive guidance", desc: "Your plan adjusts as you go — based on your progress, your energy, and your consistency." },
    { title: "Support when you need it", desc: "If you feel stuck, tired, or miss a day — your plan helps you get back on track." }
  ],
  socialText: "Millions of people have already started their journey",
  socialSub: "And many have seen real progress over time.",
  socialCta: "Get started now",
  ratingsHeadline: "15,500+",
  ratingsSubline: "five-star ratings",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Play Store",
  ratingsQuote: "The most effective weight loss assistant.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Real stories from people using Zero Carbs Challenge",
  storiesSubheading: "We are proud of these results and cannot wait to see yours.",
  verifiedCustomer: "Verified customer",
  choosePlanAria: "Choose your plan",
  savingsText: "You save __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "Secure checkout",
  trustCancelAnytime: "Cancel anytime",
  trustInstantAccess: "Instant access",
  footerLanguageLabel: "Language",
  secretGiftPill: "Get secret gift!",
  secretGiftLead: "If you select 3-month plan:",
  secretGiftTitle: "Secret gift",
  secretGiftBody: "The Zero Carbs Challenge team wants to support your relationship with food transformation and prepared a secret surprise for you.",
  giftSectionTitle: "Buy 3 month plan and get",
  giftSectionHighlight: "SECRET gift",
  giftSectionWorth: " (worth $50)",
  giftSectionBody: "The Zero Carbs Challenge team wants to support your relationship with food transformation and prepared a secret surprise for you.",
  guaranteePrefix: "Find more about applicable limitations in our",
  personalHeading: (name) => "__NAME__, build real results at your own pace".replace("__NAME__", String(name)),
  guaranteeTitle: "30-Day Money-Back Guarantee",
  guaranteeBody: "Try Zero Carbs Challenge with no risk. If it is not the right fit for you, you can request a refund within 30 days. Please check our Refund Policy for full details.",
  guaranteeLinkLabel: "money-back policy",
  footer: "© 2026 Zero Carbs Challenge. All rights reserved.",
  goalLabels: { "lose-weight":"Lose weight", "heart-health":"Improve heart health", "firm-toned":"Get more toned", "lower-bio-age":"Feel younger & energized" },
  sleepLabels: { "less-than-5":"Poor", "<5":"Poor", "5-6":"Needs improvement", "7-8":"Good", "8-9":"Good", "9+":"Could be better" },
  fitnessLabels: { sedentary:"Low", "lightly-active":"Low", light:"Low", moderate:"Medium", intermediate:"Medium", active:"High", "very-active":"High", advanced:"High" },
  bmi: {
    Normal: { title: "Good starting point", text: (bmi) => "Your BMI is __BMI__, which is in a normal range. You are on the right track. Your plan will be adjusted to fit your needs and help you keep your progress.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Good starting point", text: (bmi) => "Your BMI is __BMI__, which is below the usual range. Your plan will focus on building strength and balanced nutrition.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "A good point to make a change", text: (bmi) => "Your BMI is __BMI__. With the right routine, you can improve how your body feels. We will guide you step by step with a plan that fits your daily life.".replace("__BMI__", String(bmi)) },
    Obese: { title: "A good time to take care of your body", text: (bmi) => "Your BMI is __BMI__. With the right plan, you can improve how your body feels and moves. We will guide you with small, simple steps that fit your daily life.".replace("__BMI__", String(bmi)) }
  },
}

export function localize(base, overrides) {
  return {
    ...base,
    ...overrides,
    plans: overrides.plans ?? base.plans,
    features: overrides.features ?? base.features,
    goalLabels: overrides.goalLabels ?? base.goalLabels,
    sleepLabels: overrides.sleepLabels ?? base.sleepLabels,
    fitnessLabels: overrides.fitnessLabels ?? base.fitnessLabels,
    bmi: overrides.bmi ?? base.bmi,
  }
}

export const COPY: Record<LangCode, Copy> = {
  en: EN,
  lt: {
  plans: [
    { name: "7 dienų planas", desc: "1.09 USD per dieną", badge: "Populiariausias – sutaupykite daugiau nei 50 %" },
    { name: "1 mėnesio planas", desc: "0.61 USD per dieną", badge: null },
    { name: "3 mėnesių planas", desc: "0.31 USD per dieną", badge: "Geriausias pasiūlymas" }
  ],
  pageTitle: "Jūsų asmeninis beangliavandenio iššūkio planas paruoštas",
  pageSub: "Pasirinkite sau tinkamiausią planą.",
  stickyTimerLabel: "Speciali 50 % nuolaida galioja:",
  stickyMinutesLabel: "minutės",
  stickySecondsLabel: "sekundės",
  beforeLabel: "Dabar",
  afterLabel: "Tikslas",
  bodyFatLabel: "Kūno riebalai",
  bodyFatHigh: "Daug",
  bodyFatNormal: "Normalu",
  bodyFatLow: "Mažai",
  fitnessLevelLabel: "Fizinis pasiruošimas",
  fitnessLevelBeginner: "Pradedantysis",
  fitnessLevelIntermediate: "Pažengęs",
  fitnessLevelAdvanced: "Profesionalas",
  discount: (v) => "su __V__ nuolaida".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ per dieną".replace("__V__", String(v)),
  moneyBackRow: "30 dienų pinigų grąžinimo garantija – išbandykite be rizikos. Jei planas jums netiks, grąžinsime pinigus.",
  cta: "Gauti mano planą",
  consentPrefix: "Tęsdami jūs sutinkate su mūsų",
  terms: "Naudojimo sąlygomis",
  privacy: "Privatumo politika",
  refund: "Pinigų grąžinimo politika",
  consentAnd: "ir",
  consentError: "Kad tęstumėte, sutikite su sąlygomis.",
  consentBody: (today, renew) => "Tai automatiškai pratęsiama prenumerata. Šiandien iš jūsų bus nuskaičiuota __TODAY__. Pasibaigus plano laikotarpiui, prenumerata bus pratęsta už __RENEW__, nebent ją atšauksite. Atšaukti galite bet kada likus bent 48 valandoms iki pratęsimo, susisiekę su klientų aptarnavimo tarnyba el. paštu:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Jūsų rezultatai",
  primaryGoal: "PAGRINDINIS TIKSLAS",
  fitnessLevel: "FIZINIS PASIRUOŠIMAS",
  sleepQuality: "MIEGO KOKYBĖ",
  fitnessAge: "KŪNO BIOLOGINIS AMŽIUS",
  fitnessAgeValue: (years) => "__YEARS__ metais/-ų vyresnis nei jūsų faktinis amžius".replace("__YEARS__", String(years)),
  workoutTitle: "Jūsų asmeninis beangliavandenio iššūkio planas",
  workoutBadge: "REKOMENDUOJAMA TRENIRUOTĖS TRUKMĖ",
  waterTitle: "Vandens suvartojimas",
  waterBadge: "REKOMENDUOJAMA VANDENS NORMA PER DIENĄ",
  readyHeading: "Jūsų planas su beangliavandeniu iššūkiu paruoštas!",
  bulletTitle: "Su beangliavandeniu iššūkiu galėsite:",
  bullets: ["Daugiau pasitikėjimo savimi", "Daugiau energijos", "Mažiau streso", "Geresnė savijauta ilgą laiką"],
  whatYouGet: "Ką gausite su beangliavandeniu iššūkiu",
  phoneMealTag: "Pusryčiai",
  phoneMealTitle: "Kepta lašiša su šparaginėmis pupelėmis",
  phoneMealMeta: "4.8 · 10 min · 498 kcal",
  phoneIngredientsTab: "Ingredientai",
  phoneNutritionTab: "Maistinė vertė",
  phoneIngredient1: "Šparaginės pupelės",
  phoneIngredient1Qty: "1 puodelis",
  phoneIngredient2: "Citrina",
  phoneIngredient2Qty: "1 vidutinė",
  phoneIngredient3: "Sezamo sėklos",
  phoneIngredient3Qty: "1 valg. š.",
  phoneIngredient4: "Alyvuogių aliejus",
  phoneIngredient4Qty: "3 1/2 arb. š.",
  features: [
    { title: "Asmeninis planas", desc: "Jūsų planas sukurtas atsižvelgiant į jūsų kūną, energiją ir kasdienį gyvenimą, o ne pagal šabloną." },
    { title: "Paprasti kasdieniai patarimai", desc: "Jums nereikės nieko planuoti patiems – visada žinosite, ką daryti šiandien." },
    { title: "Prisitaikantis vadovavimas", desc: "Jūsų planas bus koreguojamas atsižvelgiant į jūsų pažangą, savijautą ir pastangas." },
    { title: "Pagalba, kai jos reikia", desc: "Jei prarasite motyvaciją ar praleisite dieną, planas padės jums grįžti į teisingą kelią." }
  ],
  socialText: "Milijonai žmonių jau pradėjo savo kelionę",
  socialSub: "Daugeliui pavyko pasiekti akivaizdžių rezultatų.",
  socialCta: "Pradėti dabar",
  ratingsHeadline: "15,500+",
  ratingsSubline: "5 žvaigždučių įvertinimų",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Google Play",
  ratingsQuote: "Veiksmingiausias pagalbininkas metant svorį.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Tikros sėkmės istorijos naudojant beangliavandenį iššūkį",
  storiesSubheading: "Mes didžiuojamės šiais rezultatais ir tikimės, kad jūs pasieksite dar geresnių.",
  verifiedCustomer: "Patvirtintas pirkėjas",
  choosePlanAria: "Pasirinkite savo planą",
  savingsText: "Sutaupote __AMOUNT__ (__PERCENT__ %)",
  trustSecureCheckout: "Saugus apmokėjimas",
  trustCancelAnytime: "Atšaukite bet kada",
  trustInstantAccess: "Greita prieiga",
  footerLanguageLabel: "Kalba",
  secretGiftPill: "Gaukite slapta dovaną!",
  secretGiftLead: "Jei pasirinksite 3 mėnesių planą:",
  secretGiftTitle: "Slapta dovana",
  secretGiftBody: "Beangliavandenio iššūkio komanda nori palaikyti jūsų pokyčius ir paruošė jums staigmeną.",
  giftSectionTitle: "Gaukite SLAPTA dovaną su",
  giftSectionHighlight: "3 mėnesių planu",
  giftSectionWorth: " (50 USD vertės)",
  giftSectionBody: "Beangliavandenio iššūkio komanda nori palaikyti jūsų pokyčius ir paruošė jums staigmeną.",
  guaranteePrefix: "Sužinokite daugiau apie taikomus apribojimus mūsų",
  personalHeading: (name) => "__NAME__, pasiekite rezultatų savo tempu".replace("__NAME__", String(name)),
  guaranteeTitle: "30 dienų pinigų grąžinimo garantija",
  guaranteeBody: "Išbandykite beangliavandenį iššūkį be rizikos. Jei jis jums netiks, galite kreiptis dėl pinigų grąžinimo per 30 dienų. Išsamią informaciją rasite mūsų pinigų grąžinimo politikoje.",
  guaranteeLinkLabel: "pinigų grąžinimo taisyklėse",
  footer: "© 2026 beangliavandenis iššūkis. Visos teisės saugomos.",
  goalLabels: { "lose-weight":"Numesti svorio", "heart-health":"Pagerinti širdies sveikatą", "firm-toned":"Sustangrinti kūną", "lower-bio-age":"Jaustis energingiau ir jauniau" },
  sleepLabels: { "less-than-5":"Prastas", "<5":"Prastas", "5-6":"Reikėtų gerinti", "7-8":"Geras", "8-9":"Geras", "9+":"Galėtų būti geresnis" },
  fitnessLabels: { sedentary:"Žemas", "lightly-active":"Žemas", light:"Žemas", moderate:"Vidutinis", intermediate:"Vidutinis", active:"Aukštas", "very-active":"Aukštas", advanced:"Aukštas" },
  bmi: {
    Normal: { title: "Gera pradžia", text: (bmi) => "Jūsų KMI yra __BMI__, tai yra normalus svoris. Esate teisingame kelyje, o asmeninis planas padės išlaikyti pasiektą pažangą.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Gera pradžia", text: (bmi) => "Jūsų KMI yra __BMI__, tai yra mažiau nei įprasta. Jūsų planas bus orientuotas į jėgų stiprinimą ir subalansuotą mitybą.".replace("__BMI__", String(bmi)) },
    Overweight: { title: " Tinkamas laikas pokyčiams", text: (bmi) => "Jūsų KMI yra __BMI__. Pasirinkę tinkamą rutiną, galite pagerinti savo savijautą. Mes padėsime jums žingsnis po žingsnio.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Tinkamas laikas pasirūpinti savimi", text: (bmi) => "Jūsų KMI yra __BMI__. Turėdami tinkamą planą, galite pagerinti savo sveikatą ir judrumą. Padėsime jums žengti paprastus žingsnius.".replace("__BMI__", String(bmi)) }
  },
},
  lv: {
  plans: [
    { name: "7 dienu plāns", desc: "USD 1.09 / dienā", badge: "Populārākais — ietaupiet vairāk nekā 50%" },
    { name: "1 mēneša plāns", desc: "USD 0.61 / dienā", badge: null },
    { name: "3 mēnešu plāns", desc: "USD 0.31 / dienā", badge: "Labākā vērtība" }
  ],
  pageTitle: "Jūsu personalizētais Zero Carbs izaicinājuma plāns ir gatavs",
  pageSub: "Izvēlieties plānu, kas jums vislabāk atbilst.",
  stickyTimerLabel: "Jūsu īpašā 50%+ atlaide ir rezervēta:",
  stickyMinutesLabel: "minūtes",
  stickySecondsLabel: "sekundes",
  beforeLabel: "Tagad",
  afterLabel: "Mērķis",
  bodyFatLabel: "Ķermeņa tauki",
  bodyFatHigh: "Augsts",
  bodyFatNormal: "Normāls",
  bodyFatLow: "Zems",
  fitnessLevelLabel: "Fiziskās sagatavotības līmenis",
  fitnessLevelBeginner: "Iesācējs",
  fitnessLevelIntermediate: "Vidējs",
  fitnessLevelAdvanced: "Pieredzējis",
  discount: (v) => "ar __V__ atlaidi".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ dienā".replace("__V__", String(v)),
  moneyBackRow: "30 dienu naudas atgriešanas garantija — izmēģiniet bez riska. Ja tas jums nav piemērots, varat saņemt naudu atpakaļ.",
  cta: "Saņemt manu plānu",
  consentPrefix: "Turpinot, jūs piekrītat mūsu",
  terms: "Lietošanas noteikumiem",
  privacy: "Privātuma politikai",
  refund: "Atgriešanas politikai",
  consentAnd: "un",
  consentError: "Lūdzu, apstipriniet noteikumus, lai turpinātu.",
  consentBody: (today, renew) => "Šis ir abonements, kas atjaunojas automātiski. Šodien jums tiks iekasēta maksa __TODAY__. Pēc plāna perioda beigām jūsu plāns tiks atjaunots par __RENEW__, ja vien jūs to neatceļat. Jūs varat atcelt jebkurā laikā vismaz 48 stundas pirms atjaunošanas, sazinoties ar atbalsta dienestu:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Jūsu rezultāti",
  primaryGoal: "GALVENAIS MĒRĶIS",
  fitnessLevel: "FIZISKĀS SAGATAVOTĪBAS LĪMENIS",
  sleepQuality: "MIEGA KVALITĀTE",
  fitnessAge: "FIZISKAIS VECUMS",
  fitnessAgeValue: (years) => "__YEARS__ gadus vecāks nekā jūsu faktiskais vecums".replace("__YEARS__", String(years)),
  workoutTitle: "Jūsu personalizētais Zero Carbs izaicinājuma plāns",
  workoutBadge: "IETEICAMAIS TRENIŅA ILGUMS",
  waterTitle: "Ūdens uzņemšana",
  waterBadge: "IETEICAMĀ DIENAS ŪDENS DEVA",
  readyHeading: "Jūsu plāns ar Zero Carbs izaicinājumu ir gatavs!",
  bulletTitle: "Ar Zero Carbs izaicinājumu jūs varat:",
  bullets: ["Vairo pārliecību", "Uzlabo enerģiju", "Samazina stresu", "Atbalsta jūsu ķermeni laika gaitā"],
  whatYouGet: "Ko jūs iegūstat ar Zero Carbs izaicinājumu",
  phoneMealTag: "Brokastis",
  phoneMealTitle: "Cepts lasis ar zaļajām pupiņām",
  phoneMealMeta: "4.8 · 10 min · 498 kcal",
  phoneIngredientsTab: "Sastāvdaļas",
  phoneNutritionTab: "Uzturvērtība",
  phoneIngredient1: "Zaļās pupiņas",
  phoneIngredient1Qty: "1 glāze",
  phoneIngredient2: "Citrons",
  phoneIngredient2Qty: "1 vidējs",
  phoneIngredient3: "Sezama sēklas",
  phoneIngredient3Qty: "1 ēd.k.",
  phoneIngredient4: "Olīveļļa",
  phoneIngredient4Qty: "3 1/2 tējk.",
  features: [
    { title: "Personalizēts plāns", desc: "Jūsu plāns ir balstīts uz jūsu ķermeni, enerģiju un ikdienas dzīvi, nevis vispārīgu rutīnu." },
    { title: "Vienkārši dienas norādījumi", desc: "Jūs vienmēr zināt, kas šodien jādara, bez liekas domāšanas vai plānošanas." },
    { title: "Adaptīva vadība", desc: "Jūsu plāns pielāgojas procesā — balstoties uz jūsu progresu, enerģiju un konsekvenci." },
    { title: "Atbalsts, kad tas nepieciešams", desc: "Ja jūtaties iestrēdzis, noguris vai izlaižat dienu, jūsu plāns palīdz atgriezties uz pareizā ceļa." }
  ],
  socialText: "Miljoniem cilvēku jau ir sākuši savu ceļojumu",
  socialSub: "Un daudzi laika gaitā ir redzējuši reālu progresu.",
  socialCta: "Sākt tagad",
  ratingsHeadline: "15,500+",
  ratingsSubline: "5 zvaigžņu vērtējumu",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Play Store",
  ratingsQuote: "Visefektīvākais svara zaudēšanas palīgs.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Reāli stāsti no cilvēkiem, kuri izmanto Zero Carbs izaicinājumu",
  storiesSubheading: "Mēs lepojamies ar šiem rezultātiem un nevaram sagaidīt, kad redzēsim jūsējos.",
  verifiedCustomer: "Pārbaudīts klients",
  choosePlanAria: "Izvēlieties savu plānu",
  savingsText: "Jūs ietaupāt __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "Droša apmaksa",
  trustCancelAnytime: "Atcelt jebkurā laikā",
  trustInstantAccess: "Tūlītēja piekļuve",
  footerLanguageLabel: "Valoda",
  secretGiftPill: "Saņemt slepeno dāvanu!",
  secretGiftLead: "Ja izvēlaties 3 mēnešu plānu:",
  secretGiftTitle: "Slepenā dāvana",
  secretGiftBody: "Zero Carbs izaicinājuma komanda vēlas atbalstīt jūsu attiecību ar ēdienu transformāciju un ir sagatavojusi jums slepenu pārsteigumu.",
  giftSectionTitle: "Pērc 3 mēnešu plānu un saņem",
  giftSectionHighlight: "SLEPENO dāvanu",
  giftSectionWorth: " ($50 vērtībā)",
  giftSectionBody: "Zero Carbs izaicinājuma komanda vēlas atbalstīt jūsu attiecību ar ēdienu transformāciju un ir sagatavojusi jums slepenu pārsteigumu.",
  guaranteePrefix: "Uzziniet vairāk par piemērojamajiem ierobežojumiem mūsu",
  personalHeading: (name) => "__NAME__, gūstiet reālus rezultātus savā tempā".replace("__NAME__", String(name)),
  guaranteeTitle: "30 dienu naudas atgriešanas garantija",
  guaranteeBody: "Izmēģiniet Zero Carbs izaicinājumu bez riska. Ja tas jums nav piemērots, varat pieprasīt naudas atgriešanu 30 dienu laikā. Lūdzu, pārbaudiet mūsu Atgriešanas politiku, lai uzzinātu visas detaļas.",
  guaranteeLinkLabel: "naudas atgriešanas politiku",
  footer: "© 2026 Zero Carbs izaicinājums. Visas tiesības aizsargātas.",
  goalLabels: { "lose-weight":"Zaudēt svaru", "heart-health":"Uzlabot sirds veselību", "firm-toned":"Kļūt tvirtākam/-ai", "lower-bio-age":"Justies jaunākam/-ai un enerģētiskākam/-ai" },
  sleepLabels: { "less-than-5":"Slikts", "<5":"Slikts", "5-6":"Nepieciešami uzlabojumi", "7-8":"Labs", "8-9":"Labs", "9+":"Varētu būt labāks" },
  fitnessLabels: { sedentary:"Zems", "lightly-active":"Zems", light:"Zems", moderate:"Vidējs", intermediate:"Vidējs", active:"Augsts", "very-active":"Augsts", advanced:"Augsts" },
  bmi: {
    Normal: { title: "Labs sākuma punkts", text: (bmi) => "Jūsu ĶMI ir __BMI__, kas ir normālā diapazonā. Jūs esat uz pareizā ceļa. Jūsu plāns tiks pielāgots jūsu vajadzībām, lai palīdzētu saglabāt progresu.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Labs sākuma punkts", text: (bmi) => "Jūsu ĶMI ir __BMI__, kas ir zem parastā diapazona. Jūsu plāns būs vērsts uz spēka veidošanu un sabalansētu uzturu.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "Labs laiks, lai veiktu izmaiņas", text: (bmi) => "Jūsu ĶMI ir __BMI__. Ar pareizo rutīnu jūs varat uzlabot sava ķermeņa pašsajūtu. Mēs vadīsim jūs soli pa solim ar plānu, kas atbilst jūsu ikdienas dzīvei.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Labs laiks, lai parūpētos par savu ķermeni", text: (bmi) => "Jūsu ĶMI ir __BMI__. Ar pareizo plānu jūs varat uzlabot sava ķermeņa pašsajūtu un kustības. Mēs vadīsim jūs ar maziem, vienkāršiem soļiem, kas atbilst jūsu ikdienas dzīvei.".replace("__BMI__", String(bmi)) }
  },
},
  ro: {
  plans: [
    { name: "Plan de 7 zile", desc: "USD 1.09 / zi", badge: "Cel mai popular — economisește peste 50%" },
    { name: "Plan de 1 lună", desc: "USD 0.61 / zi", badge: null },
    { name: "Plan de 3 luni", desc: "USD 0.31 / zi", badge: "Cea mai bună ofertă" }
  ],
  pageTitle: "Planul tău personalizat pentru Provocarea Fără Carbohidrați este gata",
  pageSub: "Alege planul care ți se potrivește cel mai bine.",
  stickyTimerLabel: "Reducerea ta specială de 50%+ este rezervată pentru:",
  stickyMinutesLabel: "minute",
  stickySecondsLabel: "secunde",
  beforeLabel: "Acum",
  afterLabel: "Obiectiv",
  bodyFatLabel: "Grăsime corporală",
  bodyFatHigh: "Ridicată",
  bodyFatNormal: "Normală",
  bodyFatLow: "Scăzută",
  fitnessLevelLabel: "Nivel de fitness",
  fitnessLevelBeginner: "Începător",
  fitnessLevelIntermediate: "Intermediar",
  fitnessLevelAdvanced: "Avansat",
  discount: (v) => "cu __V__ reducere".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ pe zi".replace("__V__", String(v)),
  moneyBackRow: "Garanție de returnare a banilor timp de 30 de zile — Încearcă fără riscuri. Dacă nu ți se potrivește, primești banii înapoi.",
  cta: "Obține planul meu",
  consentPrefix: "Continuând, ești de acord cu",
  terms: "Termenii de utilizare",
  privacy: "Politica de confidențialitate",
  refund: "Politica de rambursare",
  consentAnd: "și",
  consentError: "Te rugăm să accepți termenii pentru a continua.",
  consentBody: (today, renew) => "Acesta este un abonament care se reînnoiește automat. Vei fi taxat cu __TODAY__ astăzi. După terminarea perioadei planului, acesta se va reînnoi la prețul de __RENEW__, cu excepția cazului în care anulezi. Poți anula oricând cu cel puțin 48 de ore înainte de reînnoire, contactând serviciul de asistență prin e-mail:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Rezultatele tale",
  primaryGoal: "OBIECTIV PRINCIPAL",
  fitnessLevel: "NIVEL DE FITNESS",
  sleepQuality: "CALITATEA SOMNULUI",
  fitnessAge: "VÂRSTA DE FITNESS",
  fitnessAgeValue: (years) => "cu __YEARS__ ani mai mare decât vârsta ta reală".replace("__YEARS__", String(years)),
  workoutTitle: "Planul tău personalizat pentru Provocarea Fără Carbohidrați",
  workoutBadge: "DURATA RECOMANDATĂ A ANTRENAMENTULUI",
  waterTitle: "Consumul de apă",
  waterBadge: "CONSUMUL ZILNIC RECOMANDAT DE APĂ",
  readyHeading: "Planul tău cu Provocarea Fără Carbohidrați este gata!",
  bulletTitle: "Cu Provocarea Fără Carbohidrați poți:",
  bullets: ["Capătă încredere în sine", "Îmbunătățește-ți nivelul de energie", "Redu stresul", "Susține-ți corpul în timp"],
  whatYouGet: "Ce primești cu Provocarea Fără Carbohidrați",
  phoneMealTag: "Mic dejun",
  phoneMealTitle: "Somon prăjit cu fasole verde",
  phoneMealMeta: "4.8 · 10 min · 498 kcal",
  phoneIngredientsTab: "Ingrediente",
  phoneNutritionTab: "Valori nutriționale",
  phoneIngredient1: "Fasole verde",
  phoneIngredient1Qty: "1 cană",
  phoneIngredient2: "Lămâie",
  phoneIngredient2Qty: "1 medie",
  phoneIngredient3: "Semințe de susan",
  phoneIngredient3Qty: "1 lingură",
  phoneIngredient4: "Ulei de măsline",
  phoneIngredient4Qty: "3 1/2 lingurițe",
  features: [
    { title: "Un plan personalizat", desc: "Planul tău este construit în funcție de corpul tău, energia ta și viața ta de zi cu zi — nu o rutină generică." },
    { title: "Îndrumări zilnice simple", desc: "Știi mereu ce ai de făcut astăzi, fără să stai pe gânduri sau să planifici." },
    { title: "Ghidare adaptivă", desc: "Planul tău se adaptează pe parcurs — în funcție de progresul tău, energie și consecvență." },
    { title: "Asistență când ai nevoie", desc: "Dacă te simți blocat, obosit sau pierzi o zi — planul tău te ajută să revii pe drumul cel bun." }
  ],
  socialText: "Milioane de oameni și-au început deja călătoria",
  socialSub: "Și mulți au văzut progrese reale în timp.",
  socialCta: "Începe acum",
  ratingsHeadline: "15.500+",
  ratingsSubline: "evaluări de 5 stele",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Google Play",
  ratingsQuote: "Cel mai eficient asistent pentru pierderea în greutate.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Povești reale de la oameni care folosesc Provocarea Fără Carbohidrați",
  storiesSubheading: "Suntem mândri de aceste rezultate și abia așteptăm să le vedem pe ale tale.",
  verifiedCustomer: "Client verificat",
  choosePlanAria: "Alege planul tău",
  savingsText: "Economisești __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "Plată securizată",
  trustCancelAnytime: "Anulează oricând",
  trustInstantAccess: "Acces instantaneu",
  footerLanguageLabel: "Limba",
  secretGiftPill: "Primește un cadou secret!",
  secretGiftLead: "Dacă alegi un plan de 3 luni:",
  secretGiftTitle: "Cadou secret",
  secretGiftBody: "Echipa Provocării Fără Carbohidrați dorește să îți susțină transformarea relației cu mâncarea și ți-a pregătit o surpriză secretă.",
  giftSectionTitle: "Cumpără planul de 3 luni și primești un",
  giftSectionHighlight: "CADOU SECRET",
  giftSectionWorth: " (în valoare de 50$)",
  giftSectionBody: "Echipa Provocării Fără Carbohidrați dorește să îți susțină transformarea relației cu mâncarea și ți-a pregäti o surpriză secretă.",
  guaranteePrefix: "Află mai multe despre limitările aplicabile în",
  personalHeading: (name) => "__NAME__, obține rezultate reale în ritmul tău".replace("__NAME__", String(name)),
  guaranteeTitle: "Garanție de returnare a banilor timp de 30 de zile",
  guaranteeBody: "Încearcă Provocarea Fără Carbohidrați fără riscuri. Dacă nu este pentru tine, poți solicita o rambursare în termen de 30 de zile. Te rugăm să verifici Politica noastră de rambursare pentru toate detaliile.",
  guaranteeLinkLabel: "politica de returnare a banilor",
  footer: "© 2026 Provocarea Fără Carbohidrați. Toate drepturile rezervate.",
  goalLabels: { "lose-weight":"Să pierd în greutate", "heart-health":"Îmbunătățirea sănătății inimii", "firm-toned":"Tonifierea corpului", "lower-bio-age":"Să mă simt mai tânăr(ă) și plin(ă) de energie" },
  sleepLabels: { "less-than-5":"Slab", "<5":"Slab", "5-6":"Necesită îmbunătățiri", "7-8":"Bun", "8-9":"Bun", "9+":"Ar putea fi mai bine" },
  fitnessLabels: { sedentary:"Scăzut", "lightly-active":"Scăzut", light:"Scăzut", moderate:"Mediu", intermediate:"Mediu", active:"Ridicată", "very-active":"Ridicată", advanced:"Ridicată" },
  bmi: {
    Normal: { title: "Un punct de plecare bun", text: (bmi) => "IMC-ul tău este de __BMI__, ceea ce reprezintă un interval normal. Ești pe drumul cel bun. Planul tău va fi adaptat nevoilor tale pentru a te ajuta să menții progresul.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Un punct de plecare bun", text: (bmi) => "IMC-ul tău este de __BMI__, ceea ce este sub intervalul obișnuit. Planul tău se va concentra pe dezvoltarea forței și o nutriție echilibrată.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "Un moment bun pentru o schimbare", text: (bmi) => "IMC-ul tău este de __BMI__. Cu rutina potrivită, poți îmbunătăți starea corpului tău. Te vom ghida pas cu pas cu un plan care se potrivește vieții tale de zi cu zi.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Un moment bun să ai grijă de corpul tău", text: (bmi) => "IMC-ul tău este de __BMI__. Cu planul potrivit, poți îmbunătăți felul în care te simți și te miști. Te vom ghida prin pași mici și simpli, adaptați vieții tale.".replace("__BMI__", String(bmi)) }
  },
},
  cz: {
  plans: [
    { name: "7denní plán", desc: "1,09 USD / den", badge: "Nejoblíbenější — ušetřete více než 50 %" },
    { name: "1měsíční plán", desc: "0,61 USD / den", badge: null },
    { name: "3měsíční plán", desc: "0,31 USD / den", badge: "Nejlepší nabídka" }
  ],
  pageTitle: "Váš personalizovaný plán výzvy bez sacharidů je připraven",
  pageSub: "Vyberte si plán, který Vám nejvíce vyhovuje.",
  stickyTimerLabel: "Vaše speciální sleva 50%+ je rezervována na:",
  stickyMinutesLabel: "minut",
  stickySecondsLabel: "sekund",
  beforeLabel: "Nyní",
  afterLabel: "Cíl",
  bodyFatLabel: "Tělesný tuk",
  bodyFatHigh: "Vysoký",
  bodyFatNormal: "Normální",
  bodyFatLow: "Nízký",
  fitnessLevelLabel: "Úroveň kondice",
  fitnessLevelBeginner: "Začátečník",
  fitnessLevelIntermediate: "Pokročilý",
  fitnessLevelAdvanced: "Expert",
  discount: (v) => "se slevou __V__".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ za den".replace("__V__", String(v)),
  moneyBackRow: "30denní záruka vrácení peněz — vyzkoušejte bez rizika. Pokud Vám plán nebude vyhovovat, vrátíme Vám peníze.",
  cta: "Získat můj plán",
  consentPrefix: "Pokračováním souhlasíte s našimi",
  terms: "Smluvními podmínkami",
  privacy: "Zásadami ochrany osobních údajov",
  refund: "Zásadami vrácení platby",
  consentAnd: "a",
  consentError: "Pokud chcete pokračovat, přijměte smluvní podmínky.",
  consentBody: (today, renew) => "Toto je předplatné, které se automaticky obnovuje. Dnes Vám bude účtována částka __TODAY__. Po skončení období se Váš plán obnoví za cenu __RENEW__, pokud jej nezrušíte. Plán můžete zrušit kdykoli, nejméně 48 hodin před obnovením, kontaktováním podpory e-mailem:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Vaše výsledky",
  primaryGoal: "HLAVNÍ CÍL",
  fitnessLevel: "ÚROVEŇ KONDICE",
  sleepQuality: "KVALITA SPÁNKU",
  fitnessAge: "KONDICIÁLNÍ VĚK",
  fitnessAgeValue: (years) => "o __YEARS__ let vyšší než Váš skutečný věk".replace("__YEARS__", String(years)),
  workoutTitle: "Váš personalizovaný plán výzvy bez sacharidů",
  workoutBadge: "DOPORUČENÁ DÉLKA TRÉNINKU",
  waterTitle: "Příjem vody",
  waterBadge: "DOPORUČENÝ DENNÍ PŘÍJEM VODY",
  readyHeading: "Váš plán s výzvou bez sacharidů je připraven!",
  bulletTitle: "S výzvou bez sacharidů můžete:",
  bullets: ["Získejte sebevědomí", "Zvyšte svou energii", "Snižte stres", "Podpořte své tělo dlouhodobě"],
  whatYouGet: "Co získáte s výzvou bez sacharidů",
  phoneMealTag: "Snídaně",
  phoneMealTitle: "Pečený losos se zelenými fazolkami",
  phoneMealMeta: "4.8 · 10 min · 498 kcal",
  phoneIngredientsTab: "Ingredience",
  phoneNutritionTab: "Nutriční hodnoty",
  phoneIngredient1: "Zelené fazolky",
  phoneIngredient1Qty: "1 šálek",
  phoneIngredient2: "Citron",
  phoneIngredient2Qty: "1 střední",
  phoneIngredient3: "Sezamová semínka",
  phoneIngredient3Qty: "1 PL",
  phoneIngredient4: "Olivový olej",
  phoneIngredient4Qty: "3 1/2 ČL",
  features: [
    { title: "Personalizovaný plán", desc: "Váš plán je sestaven na míru Vašemu tělu, energii a každodennímu životu – není to žádný generický postup." },
    { title: "Jednoduché denní pokyny", desc: "Vždy víte, co máte v daný den udělat, bez zbytečného přemýšlení či plánování." },
    { title: "Adaptivní vedení", desc: "Váš plán se průběžne přizpůsobuje – na základě Vašeho pokroku, energie a důslednosti." },
    { title: "Podpora, když ji potřebujete", desc: "Pokud se cítíte zaseknutí, unavení nebo vynecháte den – Váš plán Vám pomůže vrátit se zpět na cestu." }
  ],
  socialText: "Miliony lidí již začaly svou cestu",
  socialSub: "Mnozí zaznamenali reálný pokrok v průběhu času.",
  socialCta: "Začít nyní",
  ratingsHeadline: "15 500+",
  ratingsSubline: "5hvězdičkových hodnocení",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Google Play",
  ratingsQuote: "Neúčinnější pomocník při hubnutí.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Skutečné příběhy lidí, kteří využívají výzvu bez sacharidů",
  storiesSubheading: "Jsme hrdí na tyto výsledky a těšíme se na ty Vaše.",
  verifiedCustomer: "Ověřený zákazník",
  choosePlanAria: "Vyberte si svůj plán",
  savingsText: "Ušetříte __AMOUNT__ (__PERCENT__ %)",
  trustSecureCheckout: "Bezpečná platba",
  trustCancelAnytime: "Zrušit kdykoli",
  trustInstantAccess: "Okamžitý přístup",
  footerLanguageLabel: "Jazyk",
  secretGiftPill: "Získejte tajný dárek!",
  secretGiftLead: "Pokud si vyberete 3měsíční plán:",
  secretGiftTitle: "Tajný dárek",
  secretGiftBody: "Tým výzvy bez sacharidů chce podpořit Vaši změnu a připravil pro Vás tajné překvapení.",
  giftSectionTitle: "Kupte si 3měsíční plán a získejte",
  giftSectionHighlight: "TAJNÝ dárek",
  giftSectionWorth: " (v hodnotě 50 USD)",
  giftSectionBody: "Tým výzvy bez sacharidů chce podpořit Vaši změnu a připravil pro Vás tajné překvapenie.",
  guaranteePrefix: "Více o platných omezeních v našich",
  personalHeading: (name) => "__NAME__, dosáhněte skutečných výsledků vlastním tempem".replace("__NAME__", String(name)),
  guaranteeTitle: "30denní záruka vrácení peněz",
  guaranteeBody: "Vyzkoušejte výzvu bez sacharidů bez rizika. Pokud Vám nebude vyhovovat, můžete požádat o vrácení peněz do 30 dnů. Podrobnosti naleznete v našich zásadách vrácení platby.",
  guaranteeLinkLabel: "zásadách vrácení peněz",
  footer: "© 2026 výzva bez sacharidů. Všechna práva vyhrazena.",
  goalLabels: { "lose-weight":"Zhubnout", "heart-health":"Zlepšit zdraví srdce", "firm-toned":"Zpevnit postavu", "lower-bio-age":"Cítit se mladší a energičtější" },
  sleepLabels: { "less-than-5":"Slabá", "<5":"Slabá", "5-6":"Vyžaduje zlepšení", "7-8":"Dobrá", "8-9":"Dobrá", "9+":"Mohla by být lepší" },
  fitnessLabels: { sedentary:"Nízká", "lightly-active":"Nízká", light:"Nízká", moderate:"Střední", intermediate:"Střední", active:"Vysoká", "very-active":"Vysoká", advanced:"Vysoká" },
  bmi: {
    Normal: { title: "Dobrý počáteční bod", text: (bmi) => "Vaše BMI je __BMI__, což je v normálním rozmezí. Jste na správné cestě. Váš plán bude přizpůsoben Vašim potřebám, aby Vám pomohl udržet progres.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Dobrý počáteční bod", text: (bmi) => "Vaše BMI je __BMI__, což je pod normálním rozmezím. Váš plán se zaměří na budování síly a vyváženou výživu.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "Vhodný čas na změnu", text: (bmi) => "Vaše BMI je __BMI__. Se správnou rutinou můžete zlepšit to, jak se Vaše tělo cítí. Povedeme Vás krok za krokem s plánem, který vyhovuje Vašemu životu.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Vhodný čas postarat se o své tělo", text: (bmi) => "Vaše BMI je __BMI__. Se správným plánem můžete zlepšit své pocity a pohyb. Povedeme Vás malými, jednoduchými kroky přizpůsobenými Vašemu životu.".replace("__BMI__", String(bmi)) }
  },
},
  dk: {
  plans: [
    { name: "7-dages plan", desc: "USD 1,09 / dag", badge: "Mest populær — spar over 50%" },
    { name: "1-måneds plan", desc: "USD 0,61 / dag", badge: null },
    { name: "3-måneders plan", desc: "USD 0,31 / dag", badge: "Bedste værdi" }
  ],
  pageTitle: "Din personlige Zero Carbs-udfordring plan er klar",
  pageSub: "Vælg den plan, der passer dig bedst.",
  stickyTimerLabel: "Din særlige 50%+ rabat er reserveret i:",
  stickyMinutesLabel: "minutter",
  stickySecondsLabel: "sekunder",
  beforeLabel: "Nu",
  afterLabel: "Mål",
  bodyFatLabel: "Kropsfedt",
  bodyFatHigh: "Højt",
  bodyFatNormal: "Normalt",
  bodyFatLow: "Lavt",
  fitnessLevelLabel: "Fitnessniveau",
  fitnessLevelBeginner: "Begynder",
  fitnessLevelIntermediate: "Øvet",
  fitnessLevelAdvanced: "Avanceret",
  discount: (v) => "med __V__ rabat".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ pr. dag".replace("__V__", String(v)),
  moneyBackRow: "30-dages pengene-tilbage-garanti — Prøv det uden risiko. Hvis det ikke er det rigtige for dig, kan du få dine penge tilbage.",
  cta: "Hent min plan",
  consentPrefix: "Ved at fortsætte accepterer du vores",
  terms: "Brugsvilkår",
  privacy: "Privatlivspolitik",
  refund: "Refusionspolitik",
  consentAnd: "og",
  consentError: "Accepter venligst vilkårene for at fortsætte.",
  consentBody: (today, renew) => "Dette er et abonnement, der fornyes automatisk. Du vil blive opkrævet __TODAY__ i dag. Når planens periode slutter, fornyes din plan til __RENEW__, medmindre du opsiger. Du kan opsige når som helst mindst 48 timer før fornyelse ved at kontakte support-e-mail:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Dine resultater",
  primaryGoal: "PRIMÆRT MÅL",
  fitnessLevel: "FITNESSNIVEAU",
  sleepQuality: "SØVNKVALITET",
  fitnessAge: "FITNESSALDER",
  fitnessAgeValue: (years) => "__YEARS__ år ældre end din faktiske alder".replace("__YEARS__", String(years)),
  workoutTitle: "Din personlige Zero Carbs-udfordring plan",
  workoutBadge: "ANBEFALET TRÆNINGSVARIGHED",
  waterTitle: "Vandindtag",
  waterBadge: "ANBEFALET DAGLIGT VANDINDTAG",
  readyHeading: "Din plan med Zero Carbs-udfordringen er klar!",
  bulletTitle: "Med Zero Carbs-udfordringen kan du:",
  bullets: ["Opbyg selvtillid", "Giv din energi et boost", "Reducer stress", "Støt din krop over tid"],
  whatYouGet: "Hvad du får med Zero Carbs-udfordringen",
  phoneMealTag: "Morgenmad",
  phoneMealTitle: "Stegt laks med grønne bønner",
  phoneMealMeta: "4.8 · 10 min · 498 kcal",
  phoneIngredientsTab: "Ingredienser",
  phoneNutritionTab: "Næringsindhold",
  phoneIngredient1: "Grønne bønner",
  phoneIngredient1Qty: "1 kop",
  phoneIngredient2: "Citron",
  phoneIngredient2Qty: "1 mellem",
  phoneIngredient3: "Sesamfrø",
  phoneIngredient3Qty: "1 spsk",
  phoneIngredient4: "Olivenolie",
  phoneIngredient4Qty: "3 1/2 tsk",
  features: [
    { title: "En personlig plan", desc: "Din plan er bygget omkring din krop, din energi og din hverdag — ikke en generisk rutine." },
    { title: "Enkel daglig vejledning", desc: "Du ved altid, hvad du skal gøre i dag, uden at tænke eller planlægge." },
    { title: "Adaptiv vejledning", desc: "Din plan justeres løbende — baseret på dine fremskridt, din energi og din vedholdenhed." },
    { title: "Support når du har brug for det", desc: "Hvis du føler dig gået i stå, er træt eller misser en dag — hjælper din plan dig tilbage på sporet." }
  ],
  socialText: "Millioner af mennesker er allerede i gang",
  socialSub: "Og mange har set virkelige fremskridt over tid.",
  socialCta: "Kom i gang nu",
  ratingsHeadline: "15.500+",
  ratingsSubline: "5-stjernede anmeldelser",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Play Store",
  ratingsQuote: "Den mest effektive hjælper til vægttab.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Virkelige historier fra folk, der bruger Zero Carbs-udfordringen",
  storiesSubheading: "Vi er stolte af disse resultater og glæder os til at se dine.",
  verifiedCustomer: "Verificeret kunde",
  choosePlanAria: "Vælg din plan",
  savingsText: "Du sparer __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "Sikker betaling",
  trustCancelAnytime: "Opsig når som helst",
  trustInstantAccess: "Øjeblikkelig adgang",
  footerLanguageLabel: "Sprog",
  secretGiftPill: "Få en hemmelig gave!",
  secretGiftLead: "Hvis du vælger en 3-måneders plan:",
  secretGiftTitle: "Hemmelig gave",
  secretGiftBody: "Holdet bag Zero Carbs-udfordringen ønsker at støtte din transformation og har forberedt en hemmelig overraskelse til dig.",
  giftSectionTitle: "Køb 3-måneders plan og få en",
  giftSectionHighlight: "HEMMELIG gave",
  giftSectionWorth: " (værdi 50 USD)",
  giftSectionBody: "Holdet bag Zero Carbs-udfordringen ønsker at støtte din transformation og har forberedt en hemmelig overraskelse til dig.",
  guaranteePrefix: "Find mere om gældende begrænsninger i vores",
  personalHeading: (name) => "__NAME__, skab virkelige resultater i dit eget tempo".replace("__NAME__", String(name)),
  guaranteeTitle: "30-dages pengene-tilbage-garanti",
  guaranteeBody: "Prøv Zero Carbs-udfordringen uden risiko. Hvis det ikke er det rette for dig, kan du anmode om refusion inden for 30 dage. Tjek venligst vores refusionspolitik for alle detaljer.",
  guaranteeLinkLabel: "pengene-tilbage-politik",
  footer: "© 2026 Zero Carbs-udfordring. Alle rettigheder forbeholdes.",
  goalLabels: { "lose-weight":"Tabe mig", "heart-health":"Forbedre hjertesundhed", "firm-toned":"Blive mere tonet", "lower-bio-age":"Føle dig yngre og energisk" },
  sleepLabels: { "less-than-5":"Dårlig", "<5":"Dårlig", "5-6":"Trænger til forbedring", "7-8":"God", "8-9":"God", "9+":"Kunne være bedre" },
  fitnessLabels: { sedentary:"Lav", "lightly-active":"Lav", light:"Lav", moderate:"Middel", intermediate:"Middel", active:"Høj", "very-active":"Høj", advanced:"Høj" },
  bmi: {
    Normal: { title: "Godt udgangspunkt", text: (bmi) => "Dit BMI er __BMI__, hvilket er i det normale område. Du er på rette vej. Din plan vil blive justeret til at passe dine behov og hjælpe dig med at holde dine fremskridt.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Godt udgangspunkt", text: (bmi) => "Dit BMI er __BMI__, hvilket er under det normale område. Din plan vil fokusere på at opbygge styrke og afbalanceret ernæring.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "Et godt tidspunkt at lave en forandring", text: (bmi) => "Dit BMI er __BMI__. Med den rette rutine kan du forbedre, hvordan din krop har det. Vi vejleder dig trin for trin med en plan, der passer til din hverdag.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Et godt tidspunkt at passe på din krop", text: (bmi) => "Dit BMI er __BMI__. Med den rette plan kan du forbedre, hvordan din krop har det og bevæger sig. Vi vejleder dig med små, enkle trin, der passer til din hverdag.".replace("__BMI__", String(bmi)) }
  },
},
  gr: {
  plans: [
    { name: "Πρόγραμμα 7 ημερών", desc: "USD 1.09 / ημέρα", badge: "Το πιο δημοφιλές — κερδίστε πάνω από 50%" },
    { name: "Πρόγραμμα 1 μήνα", desc: "USD 0.61 / ημέρα", badge: null },
    { name: "Πρόγραμμα 3 μηνών", desc: "USD 0.31 / ημέρα", badge: "Καλύτερη αξία" }
  ],
  pageTitle: "Το εξατομικευμένο πρόγραμμα της Πρόκλησης Μηδενικών Υδατανθράκων είναι έτοιμο",
  pageSub: "Επιλέξτε το πρόγραμμα που σας ταιριάζει καλύτερα.",
  stickyTimerLabel: "Η ειδική σας έκπτωση 50%+ έχει δεσμευτεί για:",
  stickyMinutesLabel: "λεπτά",
  stickySecondsLabel: "δευτερόλεπτα",
  beforeLabel: "Τώρα",
  afterLabel: "Στόχος",
  bodyFatLabel: "Σωματικό λίπος",
  bodyFatHigh: "Υψηλό",
  bodyFatNormal: "Φυσιολογικό",
  bodyFatLow: "Χαμηλό",
  fitnessLevelLabel: "Επίπεδο φυσικής κατάστασης",
  fitnessLevelBeginner: "Αρχάριος",
  fitnessLevelIntermediate: "Ενδιάμεσος",
  fitnessLevelAdvanced: "Προχωρημένος",
  discount: (v) => "με έκπτωση __V__".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ ανά ημέρα".replace("__V__", String(v)),
  moneyBackRow: "Εγγύηση επιστροφής χρημάτων 30 ημερών — Δοκιμάστε το χωρίς ρίσκο. Αν δεν είναι κατάλληλο για εσάς, μπορείτε να πάρετε τα χρήματά σας πίσω.",
  cta: "Απόκτηση του προγράμματος",
  consentPrefix: "Συνεχίζοντας, συμφωνείτε με τους",
  terms: "Όρους Χρήσης",
  privacy: "Πολιτική Απορρήτου",
  refund: "Πολιτική Επιστροφών",
  consentAnd: "και",
  consentError: "Παρακαλούμε αποδεχτείτε τους όρους για να συνεχίσετε.",
  consentBody: (today, renew) => "Αυτή είναι μια συνδρομή που ανανεώνεται αυτόματα. Θα χρεωθείτε __TODAY__ σήμερα. Μετά τη λήξη της περιόδου του προγράμματος, το πρόγραμμά σας θα ανανεωθεί με __RENEW__, εκτός αν ακυρώσετε. Μπορείτε να ακυρώσετε ανά πάσα στιγμή τουλάχιστον 48 ώρες πριν την ανανέωση, επικοινωνώντας με το email υποστήριξης:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Τα αποτελέσματά σας",
  primaryGoal: "ΚΥΡΙΟΣ ΣΤΟΧΟΣ",
  fitnessLevel: "ΕΠΙΠΕΔΟ ΦΥΣΙΚΗΣ ΚΑΤΑΣΤΑΣΗΣ",
  sleepQuality: "ΠΟΙΟΤΗΤΑ ΥΠΝΟΥ",
  fitnessAge: "ΗΛΙΚΙΑ ΦΥΣΙΚΗΣ ΚΑΤΑΣΤΑΣΗΣ",
  fitnessAgeValue: (years) => "__YEARS__ χρόνια μεγαλύτερη από την πραγματική σας ηλικία".replace("__YEARS__", String(years)),
  workoutTitle: "Το εξατομικευμένο σας πρόγραμμα Πρόκλησης Μηδενικών Υδατανθράκων",
  workoutBadge: "ΣΥΝΙΣΤΩΜΕΝΗ ΔΙΑΡΚΕΙΑ ΠΡΟΠΟΝΗΣΗΣ",
  waterTitle: "Πρόσληψη Νερού",
  waterBadge: "ΣΥΝΙΣΤΩΜΕΝΗ ΗΜΕΡΗΣΙΑ ΠΡΟΣΛΗΨΗ ΝΕΡΟΥ",
  readyHeading: "Το πρόγραμμά σας με την Πρόκληση Μηδενικών Υδατανθράκων είναι έτοιμο!",
  bulletTitle: "Με την Πρόκληση Μηδενικών Υδατανθράκων, μπορείτε:",
  bullets: ["Χτίστε αυτοπεποίθηση", "Ενισχύστε την ενέργειά σας", "Μειώστε το άγχος", "Υποστηρίξτε το σώμα σας με την πάροδο του χρόνου"],
  whatYouGet: "Τι λαμβάνετε με την Πρόκληση Μηδενικών Υδατανθράκων",
  phoneMealTag: "Πρωινό",
  phoneMealTitle: "Τηγανητός Σολομός με Φασολάκια",
  phoneMealMeta: "4.8 · 10 λεπτά · 498 kcal",
  phoneIngredientsTab: "Συστατικά",
  phoneNutritionTab: "Διατροφικά στοιχεία",
  phoneIngredient1: "Φασολάκια",
  phoneIngredient1Qty: "1 φλιτζάνι",
  phoneIngredient2: "Λεμόνι",
  phoneIngredient2Qty: "1 μέτριο",
  phoneIngredient3: "Σπόροι Σουσαμιού",
  phoneIngredient3Qty: "1 κ.σ.",
  phoneIngredient4: "Ελαιόλαδο",
  phoneIngredient4Qty: "3 1/2 κ.γ.",
  features: [
    { title: "Ένα εξατομικευμένο πρόγραμμα", desc: "Το πρόγραμμά σας χτίζεται γύρω από το σώμα, την ενέργεια και την καθημερινότητά σας — όχι μια γενική ρουτίνα." },
    { title: "Απλή καθημερινή κατεύθυνση", desc: "Ξέρετε πάντα τι να κάνετε σήμερα, χωρίς να το σκέφτεστε ή να το προγραμματίζετε." },
    { title: "Προσαρμοστική καθοδήγηση", desc: "Το πρόγραμμά σας προσαρμόζεται καθώς προχωράτε — με βάση την πρόοδό σας, την ενέργειά σας και τη συνέπειά σας." },
    { title: "Υποστήριξη όταν τη χρειάζεστε", desc: "Αν νιώθετε κολλημένοι, κουρασμένοι ή χάσετε μια μέρα — το πρόγραμμά σας σας βοηθά να επανέλθετε στο σωστό δρόμο." }
  ],
  socialText: "Εκατομμύρια άνθρωποι έχουν ήδη ξεκινήσει το ταξίδι τους",
  socialSub: "Και πολλοί έχουν δει πραγματική πρόοδο με την πάροδο του χρόνου.",
  socialCta: "Ξεκινήστε τώρα",
  ratingsHeadline: "15.500+",
  ratingsSubline: "αξιολογήσεις 5 αστέρων",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Play Store",
  ratingsQuote: "Ο πιο αποτελεσματικός βοηθός απώλειας βάρους.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Πραγματικές ιστορίες από ανθρώπους που χρησιμοποιούν το Zero Carbs Challenge",
  storiesSubheading: "Είμαστε περήφανοι για αυτά τα αποτελέσματα και ανυπομονούμε να δούμε τα δικά σας.",
  verifiedCustomer: "Επιβεβαιωμένος πελάτης",
  choosePlanAria: "Επιλέξτε το πρόγραμμά σας",
  savingsText: "Εξοικονομείτε __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "Ασφαλής πληρωμή",
  trustCancelAnytime: "Ακύρωση ανά πάσα στιγμή",
  trustInstantAccess: "Άμεση πρόσβαση",
  footerLanguageLabel: "Γλώσσα",
  secretGiftPill: "Λάβετε το μυστικό δώρο!",
  secretGiftLead: "Αν επιλέξετε το 3μηνο πρόγραμμα:",
  secretGiftTitle: "Μυστικό δώρο",
  secretGiftBody: "Η ομάδα του Zero Carbs Challenge θέλει να υποστηρίξει τη μεταμόρφωση της σχέσης σας με το φαγητό και σας ετοίμασε μια μυστική έκπληξη.",
  giftSectionTitle: "Αγοράστε το 3μηνο πρόγραμμα και κερδίστε",
  giftSectionHighlight: "ΜΥΣΤΙΚΟ δώρο",
  giftSectionWorth: " (αξίας $50)",
  giftSectionBody: "Η ομάδα του Zero Carbs Challenge θέλει να υποστηρίξει τη μεταμόρφωση της σχέσης σας με το φαγητό και σας ετοίμασε μια μυστική έκπληξη.",
  guaranteePrefix: "Βρείτε περισσότερα για τους ισχύοντες περιορισμούς στην",
  personalHeading: (name) => "__NAME__, χτίστε πραγματικά αποτελέσματα με το δικό σας ρυθμό".replace("__NAME__", String(name)),
  guaranteeTitle: "Εγγύηση Επιστροφής Χρημάτων 30 Ημερών",
  guaranteeBody: "Δοκιμάστε το Zero Carbs Challenge χωρίς ρίσκο. Αν δεν σας ταιριάζει, μπορείτε να ζητήσετε επιστροφή χρημάτων εντός 30 ημερών. Ελέγξτε την Πολιτική Επιστροφών για πλήρεις λεπτομέρειες.",
  guaranteeLinkLabel: "πολιτική επιστροφής χρημάτων",
  footer: "© 2026 Zero Carbs Challenge. Με την επιφύλαξη παντός δικαιώματος.",
  goalLabels: { "lose-weight":"Απώλεια βάρους", "heart-health":"Βελτίωση της υγείας της καρδιάς", "firm-toned":"Περισσότερη γράμμωση", "lower-bio-age":"Νιώστε νεότεροι & γεμάτοι ενέργεια" },
  sleepLabels: { "less-than-5":"Κακή", "<5":"Κακή", "5-6":"Χρειάζεται βελτίωση", "7-8":"Καλή", "8-9":"Καλή", "9+":"Θα μπορούσε να είναι καλύτερη" },
  fitnessLabels: { sedentary:"Χαμηλό", "lightly-active":"Χαμηλό", light:"Χαμηλό", moderate:"Μεσαίο", intermediate:"Μεσαίο", active:"Υψηλό", "very-active":"Υψηλό", advanced:"Υψηλό" },
  bmi: {
    Normal: { title: "Καλό σημείο εκκίνησης", text: (bmi) => "Ο ΔΜΣ σας είναι __BMI__, που είναι εντός του φυσιολογικού εύρους. Είστε στο σωστό δρόμο. Το πρόγραμμά σας θα προσαρμοστεί στις ανάγκες σας και θα σας βοηθήσει να διατηρήσετε την πρόοδό σας.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Καλό σημείο εκκίνησης", text: (bmi) => "Ο ΔΜΣ σας είναι __BMI__, που είναι κάτω από το φυσιολογικό εύρος. Το πρόγραμμά σας θα εστιάσει στο χτίσιμο δύναμης και στην ισορροπημένη διατροφή.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "Μια καλή στιγμή για αλλαγή", text: (bmi) => "Ο ΔΜΣ σας είναι __BMI__. Με τη σωστή ρουτίνα, μπορείτε να βελτιώσετε το πώς νιώθει το σώμα σας. Θα σας καθοδηγήσουμε βήμα προς βήμα με ένα πρόγραμμα που ταιριάζει στην καθημερινότητά σας.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Μια καλή στιγμή να φροντίσετε το σώμα σας", text: (bmi) => "Ο ΔΜΣ σας είναι __BMI__. Με το σωστό πρόγραμμα, μπορείτε να βελτιώσετε το πώς νιώθει και κινείται το σώμα σας. Θα σας καθοδηγήσουμε με μικρά, απλά βήματα που ταιριάζουν στην καθημερινότητά σας.".replace("__BMI__", String(bmi)) }
  },
},
  hu: {
  plans: [
    { name: "7 napos csomag", desc: "USD 1,09 / nap", badge: "Legnépszerűbb — több mint 50% megtakarítás" },
    { name: "1 hónapos csomag", desc: "USD 0,61 / nap", badge: null },
    { name: "3 hónapos csomag", desc: "USD 0,31 / nap", badge: "Legjobb ár-érték" }
  ],
  pageTitle: "Elkészült a személyre szabott Zero Carbs kihívás terved",
  pageSub: "Válaszd ki a hozzád legjobban illő csomagot.",
  stickyTimerLabel: "A különleges 50%+ kedvezményed eddig él:",
  stickyMinutesLabel: "perc",
  stickySecondsLabel: "másodperc",
  beforeLabel: "Most",
  afterLabel: "Cél",
  bodyFatLabel: "Testzsír",
  bodyFatHigh: "Magas",
  bodyFatNormal: "Normál",
  bodyFatLow: "Alacsony",
  fitnessLevelLabel: "Fittségi szint",
  fitnessLevelBeginner: "Kezdő",
  fitnessLevelIntermediate: "Középhaladó",
  fitnessLevelAdvanced: "Haladó",
  discount: (v) => "__V__ kedvezménnyel".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ / nap".replace("__V__", String(v)),
  moneyBackRow: "30 napos pénzvisszafizetési garancia — Próbáld ki kockázat nélkül. Ha nem neked való, visszakaphatod a pénzed.",
  cta: "Kérem a tervemet",
  consentPrefix: "A folytatással elfogadod a(z)",
  terms: "Felhasználási feltételeket",
  privacy: "Adatvédelmi szabályzatot",
  refund: "Visszatérítési szabályzatot",
  consentAnd: "és a(z)",
  consentError: "Kérjük, a folytatáshoz fogadd el a feltételeket.",
  consentBody: (today, renew) => "Ez egy automatikusan megújuló előfizetés. Ma (__TODAY__) kerül terhelésre. A csomagidőszak végén az előfizetés __RENEW__ áron megújul, hacsak nem mondod le. Lemondás bármikor lehetséges, de legalább 48 órával a megújulás előtt vedd fel a kapcsolatot a támogatással ezen az e-mail címen:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Eredményeid",
  primaryGoal: "FŐ CÉL",
  fitnessLevel: "FITTSÉGI SZINT",
  sleepQuality: "ALVÁS MINŐSÉGE",
  fitnessAge: "FITTSÉGI KOR",
  fitnessAgeValue: (years) => "__YEARS__ évvel idősebb a valós életkorodnál".replace("__YEARS__", String(years)),
  workoutTitle: "A személyre szabott Zero Carbs kihívás terved",
  workoutBadge: "AJÁNLOTT EDZÉSIDŐ",
  waterTitle: "Vízbevitel",
  waterBadge: "AJÁNLOTT NAPI VÍZBEVITEL",
  readyHeading: "A Zero Carbs kihívás terved elkészült!",
  bulletTitle: "A Zero Carbs kihívás segítségével:",
  bullets: ["Magabiztosság építése", "Több energia", "Kevesebb stressz", "Hosszú távú támogatás a testednek"],
  whatYouGet: "Mit kapsz a Zero Carbs kihívás-ben",
  phoneMealTag: "Reggeli",
  phoneMealTitle: "Sült lazac zöldbabbal",
  phoneMealMeta: "4.8 · 10 min · 498 kcal",
  phoneIngredientsTab: "Hozzávalók",
  phoneNutritionTab: "Tápérték",
  phoneIngredient1: "Zöldbab",
  phoneIngredient1Qty: "1 csésze",
  phoneIngredient2: "Citrom",
  phoneIngredient2Qty: "1 közepes",
  phoneIngredient3: "Szezámmag",
  phoneIngredient3Qty: "1 evőkanál",
  phoneIngredient4: "Olívaolaj",
  phoneIngredient4Qty: "3 1/2 teáskanál",
  features: [
    { title: "Személyre szabott terv", desc: "A terved a testedhez, az energiaszintedhez och a mindennapjaidhoz igazodik — nem egy sablonos rutin." },
    { title: "Egyszerű napi irány", desc: "Mindig tudod, mit tegyél ma — túl sok gondolkodás och tervezés nélkül." },
    { title: "Alkalmazkodó útmutatás", desc: "A terved menet közben igazodik — a haladásod, az energiaszinted och a következetességed alapján." },
    { title: "Támogatás, amikor kell", desc: "Ha elakadsz, fáradt vagy, vagy kihagysz egy napot — a terved segít visszatalálni." }
  ],
  socialText: "Már emberek milliói indultak el az úton",
  socialSub: "És sokan idővel valódi fejlődést láttak.",
  socialCta: "Kezdj bele most",
  ratingsHeadline: "15 500+",
  ratingsSubline: "5 csillagos értékelés",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Play Store",
  ratingsQuote: "A leghatékonyabb fogyási segítő.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Valódi történetek a Zero Carbs kihívás felhasználóitól",
  storiesSubheading: "Büszkék vagyunk ezekre az eredményekre, och alig várjuk a tieidet.",
  verifiedCustomer: "Ellenőrzött vásárló",
  choosePlanAria: "Válassz csomagot",
  savingsText: "Megtakarítás: __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "Biztonságos fizetés",
  trustCancelAnytime: "Bármikor lemondható",
  trustInstantAccess: "Azonnali hozzáférés",
  footerLanguageLabel: "Nyelv",
  secretGiftPill: "Kérem a titkos ajándékot!",
  secretGiftLead: "Ha a 3 hónapos csomagot választod:",
  secretGiftTitle: "Titkos ajándék",
  secretGiftBody: "A Zero Carbs kihívás csapata szeretné támogatni az étellel való kapcsolatod átalakulását, ezért egy titkos meglepetést készített neked.",
  giftSectionTitle: "Vásárold meg a 3 hónapos csomagot och kapd meg a",
  giftSectionHighlight: "TITKOS ajándékot",
  giftSectionWorth: " (50 USD értékben)",
  giftSectionBody: "A Zero Carbs kihívás csapata szeretné támogatni az étellel való kapcsolatod átalakulását, ezért egy titkos meglepetést készített neked.",
  guaranteePrefix: "További információ a korlátozásokról itt:",
  personalHeading: (name) => "__NAME__, építs valódi eredményeket a saját tempódban".replace("__NAME__", String(name)),
  guaranteeTitle: "30 napos pénzvisszafizetési garancia",
  guaranteeBody: "Próbáld ki a Zero Carbs kihívás-et kockázat nélkül. Ha nem neked való, 30 napon belül kérhetsz visszatérítést. A részletekért nézd meg a visszatérítési szabályzatot.",
  guaranteeLinkLabel: "pénzvisszafizetési szabályzat",
  footer: "© 2026 Zero Carbs kihívás. Minden jog fenntartva.",
  goalLabels: { "lose-weight":"Fogyás", "heart-health":"Szív egészségének javítása", "firm-toned":"Feszesebb forma", "lower-bio-age":"Fiatalabbnak och energikusabbnak érezni magad" },
  sleepLabels: { "less-than-5":"Gyenge", "<5":"Gyenge", "5-6":"Fejlesztendő", "7-8":"Jó", "8-9":"Jó", "9+":"Lehetne jobb" },
  fitnessLabels: { sedentary:"Alacsony", "lightly-active":"Alacsony", light:"Alacsony", moderate:"Közepes", intermediate:"Közepes", active:"Magas", "very-active":"Magas", advanced:"Magas" },
  bmi: {
    Normal: { title: "Jó kiindulópont", text: (bmi) => "A BMI-d __BMI__, ami normál tartományban van. Jó úton jársz. A terved a szükségleteidhez igazodik, och segít megtartani a fejlődésedet.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Jó kiindulópont", text: (bmi) => "A BMI-d __BMI__, ami a szokásos tartomány alatt van. A terved az erősítésre och a kiegyensúlyozott táplálkozásra fókuszál majd.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "Jó pont a változtatáshoz", text: (bmi) => "A BMI-d __BMI__. A megfelelő rutinnal javíthatsz azon, hogyan érzi magát a tested. Lépésről lépésre vezetünk egy, a mindennapjaidhoz illő tervvel.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Itt az idő, hogy törődj a testeddel", text: (bmi) => "A BMI-d __BMI__. A megfelelő tervvel javíthatsz azon, hogyan érzi och hogyan mozog a tested. Kis, egyszerű, a mindennapokba illeszthető lépésekkel vezetünk.".replace("__BMI__", String(bmi)) }
  },
},
  hr: {
  plans: [
    { name: "7-dnevni plan", desc: "USD 1.09 / dan", badge: "Najpopularnije — uštedite preko 50%" },
    { name: "1-mjesečni plan", desc: "USD 0.61 / dan", badge: null },
    { name: "3-mjesečni plan", desc: "USD 0.31 / dan", badge: "Najbolja vrijednost" }
  ],
  pageTitle: "Vaš personalizirani plan izazova bez ugljikohidrata je spreman",
  pageSub: "Odaberite plan koji vam najbolje odgovara.",
  stickyTimerLabel: "Vaš poseban popust od 50%+ rezerviran je za:",
  stickyMinutesLabel: "minute",
  stickySecondsLabel: "sekunde",
  beforeLabel: "Sada",
  afterLabel: "Cilj",
  bodyFatLabel: "Tjelesna mast",
  bodyFatHigh: "Visoko",
  bodyFatNormal: "Normalno",
  bodyFatLow: "Nisko",
  fitnessLevelLabel: "Razina kondicije",
  fitnessLevelBeginner: "Početnik",
  fitnessLevelIntermediate: "Napredni",
  fitnessLevelAdvanced: "Profesionalac",
  discount: (v) => "uz __V__ popusta".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ dnevno".replace("__V__", String(v)),
  moneyBackRow: "30-dnevno jamstvo povrata novca — Isprobajte bez rizika. Ako vam nije po mjeri, možete dobiti svoj novac natrag.",
  cta: "Preuzmi moj plan",
  consentPrefix: "Nastavkom se slažete s našim",
  terms: "Uvjetima korištenja",
  privacy: "Pravilima privatnosti",
  refund: "Pravilima povrata",
  consentAnd: "i",
  consentError: "Molimo prihvatite uvjete za nastavak.",
  consentBody: (today, renew) => "Ovo je pretplata koja se automatski obnavlja. Danas će vam biti naplaćeno __TODAY__. Nakon završetka razdoblja plana, vaš plan će se obnoviti po cijeni od __RENEW__, osim ako ne otkažete. Možete otkazati bilo kada, najmanje 48 sati prije obnove, kontaktiranjem službe za korisnike putem e-pošte:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Vaši rezultati",
  primaryGoal: "GLAVNI CILJ",
  fitnessLevel: "RAZINA KONDICIJE",
  sleepQuality: "KVALITETA SPAVANJA",
  fitnessAge: "KONDICIJSKA DOB",
  fitnessAgeValue: (years) => "__YEARS__ godina starija od vaše stvarne dobi".replace("__YEARS__", String(years)),
  workoutTitle: "Vaš personalizirani plan izazova bez ugljikohidrata",
  workoutBadge: "PREPORUČENO TRAJANJE VJEŽBANJA",
  waterTitle: "Unos vode",
  waterBadge: "PREPORUČENI DNEVNI UNOS VODE",
  readyHeading: "Vaš plan uz izazov bez ugljikohidrata je spreman!",
  bulletTitle: "Uz izazov bez ugljikohidrata možete:",
  bullets: ["Izgradite samopouzdanje", "Povećajte svoju energiju", "Smanjite stres", "Podržite svoje tijelo tijekom vremena"],
  whatYouGet: "Što dobivate uz izazov bez ugljikohidrata",
  phoneMealTag: "Doručak",
  phoneMealTitle: "Prženi losos sa zelenim mahunama",
  phoneMealMeta: "4.8 · 10 min · 498 kcal",
  phoneIngredientsTab: "Sastojci",
  phoneNutritionTab: "Nutritivne vrijednosti",
  phoneIngredient1: "Zelene mahune",
  phoneIngredient1Qty: "1 šalica",
  phoneIngredient2: "Limun",
  phoneIngredient2Qty: "1 srednji",
  phoneIngredient3: "Sjemenke sezama",
  phoneIngredient3Qty: "1 žlica",
  phoneIngredient4: "Maslinovo ulje",
  phoneIngredient4Qty: "3 1/2 žličice",
  features: [
    { title: "Personalizirani plan", desc: "Vaš plan je izgrađen oko vašeg tijela, vaše energije i vašeg svakodnevnog života — a ne kao generička rutina." },
    { title: "Jednostavne dnevne upute", desc: "Uvijek znate što trebate učiniti danas, bez razmišljanja ili planiranja." },
    { title: "Prilagodljivo vođenje", desc: "Vaš plan se prilagođava usput — na temelju vašeg napretka, vaše energije i vaše dosljednosti." },
    { title: "Podrška kada vam je potrebna", desc: "Ako se osjećate zaglavljeno, umorno ili propustite dan — vaš plan vam pomaže da se vratite na pravi put." }
  ],
  socialText: "Milijuni ljudi su već započeli svoje putovanje",
  socialSub: "Mnogi su vidjeli stvarni napredak tijekom vremena.",
  socialCta: "Započni sada",
  ratingsHeadline: "15,500+",
  ratingsSubline: "ocjena s 5 zvjezdica",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Google Play",
  ratingsQuote: "Najučinkovitiji asistent za gubitak težine.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Stvarne priče ljudi koji koriste izazov bez ugljikohidrata",
  storiesSubheading: "Ponosni smo na ove rezultate i jedva čekamo vidjeti vaše.",
  verifiedCustomer: "Provjereni kupac",
  choosePlanAria: "Odaberite svoj plan",
  savingsText: "Uštedite __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "Sigurno plaćanje",
  trustCancelAnytime: "Otkažite bilo kada",
  trustInstantAccess: "Trenutni pristup",
  footerLanguageLabel: "Jezik",
  secretGiftPill: "Preuzmi tajni dar!",
  secretGiftLead: "Ako odaberete 3-mjesečni plan:",
  secretGiftTitle: "Tajni dar",
  secretGiftBody: "Tim izazova bez ugljikohidrata želi podržati vašu transformaciju odnosa s hranom i pripremio je tajno iznenađenje za vas.",
  giftSectionTitle: "Kupite 3-mjesečni plan i dobijte",
  giftSectionHighlight: "TAJNI dar",
  giftSectionWorth: " (vrijednost 50 USD)",
  giftSectionBody: "Tim izazova bez ugljikohidrata želi podržati vašu transformaciju odnosa s hranom i pripremio je tajno iznenađenje za vas.",
  guaranteePrefix: "Saznajte više o primjenjivim ograničenjima u našim",
  personalHeading: (name) => "__NAME__, ostvarite stvarne rezultate vlastitim tempom".replace("__NAME__", String(name)),
  guaranteeTitle: "30-dnevno jamstvo povrata novca",
  guaranteeBody: "Isprobajte izazov bez ugljikohidrata bez rizika. Ako vam nije po mjeri, možete zatražiti povrat novca u roku od 30 dana. Molimo provjerite naša Pravila povrata za sve detalje.",
  guaranteeLinkLabel: "pravilima povrata novca",
  footer: "© 2026 izazov bez ugljikohidrata. Sva prava pridržana.",
  goalLabels: { "lose-weight":"Izgubiti težinu", "heart-health":"Poboljšati zdravlje srca", "firm-toned":"Učvrstiti tijelo", "lower-bio-age":"Osjećajte se mlađe i energičnije" },
  sleepLabels: { "less-than-5":"Loše", "<5":"Loše", "5-6":"Potrebno poboljšanje", "7-8":"Dobro", "8-9":"Dobro", "9+":"Može biti bolje" },
  fitnessLabels: { sedentary:"Niska", "lightly-active":"Niska", light:"Niska", moderate:"Srednja", intermediate:"Srednja", active:"Visoka", "very-active":"Visoka", advanced:"Visoka" },
  bmi: {
    Normal: { title: "Dobra početna točka", text: (bmi) => "Vaš BMI je __BMI__, što je u normalnom rasponu. Na pravom ste putu. Vaš plan će biti prilagođen vašim potrebama kako bi vam pomogao u održavanju napretka.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Dobra početna točka", text: (bmi) => "Vaš BMI je __BMI__, što je ispod uobičajenog raspona. Vaš plan će se usredotočiti na izgradnju snage i uravnoteženu prehranu.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "Dobro vrijeme za promjenu", text: (bmi) => "Vaš BMI je __BMI__. Uz pravu rutinu, možete poboljšati kako se vaše tijelo osjeća. Vodit ćemo vas korak po korak s planom koji odgovara vašem svakodnevnom životu.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Dobro vrijeme za brigu o svom tijelu", text: (bmi) => "Vaš BMI je __BMI__. Uz pravi plan, možete poboljšati kako se vaše tijelo osjeća i kreće. Vodit ćemo vas malim, jednostavnim koracima koji odgovaraju vašem svakodnevnom životu.".replace("__BMI__", String(bmi)) }
  },
},
  il: {
  plans: [
    { name: "תוכנית ל-7 ימים", desc: "1.09 דולר ליום", badge: "הפופולרי ביותר — חסוך מעל 50%" },
    { name: "תוכנית לחודש אחד", desc: "0.61 דולר ליום", badge: null },
    { name: "תוכנית ל-3 חודשים", desc: "0.31 דולר ליום", badge: "המשתלם ביותר" }
  ],
  pageTitle: "תוכנית אתגר אפס פחמימות המותאמת אישית שלך מוכנה",
  pageSub: "בחר/י את התוכנית המתאימה לך ביותר.",
  stickyTimerLabel: "הנחת ה-50%+ המיוחדת שלך שמורה ל:",
  stickyMinutesLabel: "דקות",
  stickySecondsLabel: "שניות",
  beforeLabel: "עכשיו",
  afterLabel: "יעד",
  bodyFatLabel: "שומן גוף",
  bodyFatHigh: "גבוה",
  bodyFatNormal: "תקין",
  bodyFatLow: "נמוך",
  fitnessLevelLabel: "רמת כושר",
  fitnessLevelBeginner: "מתחיל/ה",
  fitnessLevelIntermediate: "בינוני/ת",
  fitnessLevelAdvanced: "מתקדם/ת",
  discount: (v) => "עם הנחה של __V__".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ ליום".replace("__V__", String(v)),
  moneyBackRow: "אחריות להחזר כספי למשך 30 יום — נסה/י ללא סיכון. אם זה לא מתאים לך, תוכל/י לקבל את כספך חזרה.",
  cta: "קבל/י את התוכנית שלי",
  consentPrefix: "בהמשך, אתה מסכים ל",
  terms: "תנאי השימוש",
  privacy: "מדיניות הפרטיות",
  refund: "מדיניות החזרים",
  consentAnd: "ו",
  consentError: "אנא אשר את התנאים כדי להמשיך.",
  consentBody: (today, renew) => "זהו מנוי המתחדש אוטומטית. תחויב ב-__TODAY__ היום. לאחר סיום תקופת התוכנית, התוכנית שלך תתחדש בעלות של __RENEW__, אלא אם תבטל. ניתן לבטל בכל עת לפחות 48 שעות לפני החידוש על ידי פנייה לאימייל התמיכה:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "התוצאות שלך",
  primaryGoal: "מטרה עיקרית",
  fitnessLevel: "רמת כושר",
  sleepQuality: "איכות שינה",
  fitnessAge: "גיל כושר",
  fitnessAgeValue: (years) => "__YEARS__ שנים יותר מהגיל הכרונולוגי שלך".replace("__YEARS__", String(years)),
  workoutTitle: "תוכנית אתגר אפס פחמימות המותאמת אישית שלך",
  workoutBadge: "משך אימון מומלץ",
  waterTitle: "צריכת מים",
  waterBadge: "צריכת מים יומית מומלצת",
  readyHeading: "התוכנית שלך עם אתגר אפס פחמימות מוכנה!",
  bulletTitle: "עם אתגר אפס פחמימות את/ה יכול/ה:",
  bullets: ["בנה ביטחון עצמי", "שפר את רמת האנרגיה שלך", "הפחת מתח", "תמוך בגוף שלך לאורך זמן"],
  whatYouGet: "מה מקבלים עם אתגר אפס פחמימות",
  phoneMealTag: "ארוחת בוקר",
  phoneMealTitle: "סלמון צרוב עם שעועית ירוקה",
  phoneMealMeta: "4.8 · 10 דקות · 498 קלוריות",
  phoneIngredientsTab: "מרכיבים",
  phoneNutritionTab: "ערך תזונתי",
  phoneIngredient1: "שעועית ירוקה",
  phoneIngredient1Qty: "כוס אחת",
  phoneIngredient2: "לימון",
  phoneIngredient2Qty: "1 בינוני",
  phoneIngredient3: "שומשום",
  phoneIngredient3Qty: "כף אחת",
  phoneIngredient4: "שמן זית",
  phoneIngredient4Qty: "3.5 כפיות",
  features: [
    { title: "תוכנית מותאמת אישית", desc: "התוכנית שלך בנויה סביב הגוף, האנרגיה וחיי היומיום שלך — לא שגרה גנרית." },
    { title: "הנחיות יומיות פשוטות", desc: "תמיד תדע/י מה לעשות היום, בלי לחשוב או לתכנן יותר מדי." },
    { title: "ליווי אדפטיבי", desc: "התוכנית שלך מתכווננת תוך כדי תנועה — בהתבסס על ההתקדמות, האנרגיה והעקביות שלך." },
    { title: "תמיכה כשצריך", desc: "אם את/ה מרגיש/ה תקוע/ה, עייף/ה או מפספס/ת יום — התוכנית שלך עוזרת לך לחזור למסלול." }
  ],
  socialText: "מיליוני אנשים כבר התחילו את המסע שלהם",
  socialSub: "ורבים ראו התקדמות אמיתית לאורך זמן.",
  socialCta: "התחל/י עכשיו",
  ratingsHeadline: "15,500+",
  ratingsSubline: "דירוגי 5 כוכבים",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Google Play",
  ratingsQuote: "העוזר היעיל ביותר לירידה במשקל.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "סיפורים אמיתיים מאנשים שמשתמשים באתגר אפס פחמימות",
  storiesSubheading: "אנו גאים בתוצאות האלו ומחכים לראות את שלך.",
  verifiedCustomer: "לקוח מאומת",
  choosePlanAria: "בחר את התוכנית שלך",
  savingsText: "את/ה חוסך/ת __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "תשלום מאובטח",
  trustCancelAnytime: "ביטול בכל עת",
  trustInstantAccess: "גישה מיידית",
  footerLanguageLabel: "שפה",
  secretGiftPill: "קבל/י מתנה סודית!",
  secretGiftLead: "אם תבחר/י בתוכנית ל-3 חודשים:",
  secretGiftTitle: "מתנה סודית",
  secretGiftBody: "צוות אתגר אפס פחמימות רוצה לתמוך בשינוי הקשר שלך עם אוכל והכין עבורך הפתעה סודית.",
  giftSectionTitle: "קנה/י תוכנית ל-3 חודשים וקבל/י",
  giftSectionHighlight: "מתנה סודית",
  giftSectionWorth: " (בשווי $50)",
  giftSectionBody: "צוות אתגר אפס פחמימות רוצה לתמוך בשינוי הקשר שלך עם אוכל והכין עבורך הפתעה סודית.",
  guaranteePrefix: "למדו עוד על ההגבלות החלות ב",
  personalHeading: (name) => "__NAME__, השיגו תוצאות אמיתיות בקצב שלכם".replace("__NAME__", String(name)),
  guaranteeTitle: "אחריות להחזר כספי למשך 30 יום",
  guaranteeBody: "נסו את אתגר אפס פחמימות ללא סיכון. אם זה לא מתאים לכם, תוכלו לבקש החזר תוך 30 יום. אנא בדקו את מדיניות ההחזרים שלנו לפרטים המלאים.",
  guaranteeLinkLabel: "מדיניות החזר כספי",
  footer: "© 2026 אתגר אפס פחמימות. כל הזכויות שמורות.",
  goalLabels: { "lose-weight":"לרדת במשקל", "heart-health":"שיפור בריאות הלב", "firm-toned":"חיטוב הגוף", "lower-bio-age":"להרגיש צעיר/ה ואנרגטי/ת יותר" },
  sleepLabels: { "less-than-5":"ירודה", "<5":"ירודה", "5-6":"טעונה שיפור", "7-8":"טובה", "8-9":"טובה", "9+":"יכולה להיות טובה יותר" },
  fitnessLabels: { sedentary:"נמוכה", "lightly-active":"נמוכה", light:"נמוכה", moderate:"בינונית", intermediate:"בינונית", active:"גבוהה", "very-active":"גבוהה", advanced:"גבוהה" },
  bmi: {
    Normal: { title: "נקודת התחלה טובה", text: (bmi) => "ה-BMI שלך הוא __BMI__, שזה בטווח התקין. את/ה בדרך הנכונה. התוכנית שלך תותאם לצרכים שלך כדי לעזור לך לשמור על ההתקדמות.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "נקודת התחלה טובה", text: (bmi) => "ה-BMI שלך הוא __BMI__, שזה מתחת לטווח הרגיל. התוכנית שלך תתמקד בבניית כוח ותזונה מאוזנת.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "זמן טוב לעשות שינוי", text: (bmi) => "ה-BMI שלך הוא __BMI__. עם השגרה הנכונה, תוכל/י לשפר את ההרגשה של הגוף שלך. נוביל אותך צעד אחר צעד עם תוכנית שמתאימה לחיי היומיום שלך.".replace("__BMI__", String(bmi)) },
    Obese: { title: "זמן טוב לדאוג לגוף שלך", text: (bmi) => "ה-BMI שלך הוא __BMI__. עם התוכנית הנכונה, תוכל/י לשפר את ההרגשה והתנועה של הגוף שלך. נוביל אותך בצעדים קטנים ופשוטים שמתאימים לחיים שלך.".replace("__BMI__", String(bmi)) }
  },
},
  jp: {
  plans: [
    { name: "7日間プラン", desc: "1日あたり USD 1.09", badge: "一番人気 — 50%以上節約" },
    { name: "1ヶ月プラン", desc: "1日あたり USD 0.61", badge: null },
    { name: "3ヶ月プラン", desc: "1日あたり USD 0.31", badge: "最もお得" }
  ],
  pageTitle: "パーソナライズされたZero Carbs チャレンジプランの準備ができました",
  pageSub: "最適なプランをお選びください。",
  stickyTimerLabel: "50%以上の特別割引が適用されています：",
  stickyMinutesLabel: "分",
  stickySecondsLabel: "秒",
  beforeLabel: "現在",
  afterLabel: "目標",
  bodyFatLabel: "体脂肪",
  bodyFatHigh: "高い",
  bodyFatNormal: "普通",
  bodyFatLow: "低い",
  fitnessLevelLabel: "フィットネスレベル",
  fitnessLevelBeginner: "初心者",
  fitnessLevelIntermediate: "中級者",
  fitnessLevelAdvanced: "上級者",
  discount: (v) => "__V__割引適用".replace("__V__", String(v)),
  perDay: (v) => "1日あたり 約__V__".replace("__V__", String(v)),
  moneyBackRow: "30日間返金保証 — リスクなしでお試しください。自分に合わない場合は、返金を受けることができます。",
  cta: "プランを開始する",
  consentPrefix: "続行することで、当社の",
  terms: "利用規約",
  privacy: "プライバシーポリシー",
  refund: "返金ポリシー",
  consentAnd: "および",
  consentError: "続行するには規約に同意してください。",
  consentBody: (today, renew) => "これは自動更新されるサブスクリプションです。本日__TODAY__に請求されます。プラン期間終了後は、キャンセルしない限り__RENEW__で更新されます。更新の48時間前までにサポートメールに連絡することで、いつでもキャンセル可能です：".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "結果",
  primaryGoal: "主な目標",
  fitnessLevel: "フィットネスレベル",
  sleepQuality: "睡眠の質",
  fitnessAge: "フィットネス年齢",
  fitnessAgeValue: (years) => "実年齢よりも__YEARS__歳高い".replace("__YEARS__", String(years)),
  workoutTitle: "パーソナライズされたZero Carbs チャレンジプラン",
  workoutBadge: "推奨トレーニング時間",
  waterTitle: "水分摂取",
  waterBadge: "推奨される1日の水分摂取量",
  readyHeading: "Zero Carbs チャレンジの準備が整いました！",
  bulletTitle: "Zero Carbs チャレンジでできること：",
  bullets: ["自信をつける", "活力を高める", "ストレスを軽減", "長期的な体のサポート", "健康的、かつ持続的な減量"],
  whatYouGet: "Zero Carbs チャレンジに含まれるもの",
  phoneMealTag: "朝食",
  phoneMealTitle: "鮭のソテーとさやいんげん",
  phoneMealMeta: "4.8 · 10分 · 498 kcal",
  phoneIngredientsTab: "材料",
  phoneNutritionTab: "栄養成分",
  phoneIngredient1: "さやいんげん",
  phoneIngredient1Qty: "1カップ",
  phoneIngredient2: "レモン",
  phoneIngredient2Qty: "中1個",
  phoneIngredient3: "ごま",
  phoneIngredient3Qty: "大さじ1",
  phoneIngredient4: "オリーブオイル",
  phoneIngredient4Qty: "小さじ3 1/2",
  features: [
    { title: "パーソナライズされたプラン", desc: "あなたの体、エネルギー、そして日常生活に合わせて構築されたプランです。一般的なルーチンではありません。" },
    { title: "シンプルな毎日のガイダンス", desc: "今日やるべきことが常に明確です。面倒な計画を立てる必要はありません。" },
    { title: "適応型ガイダンス", desc: "進捗、エネルギー、継続状況に基づいて、プランが動的に調整されます。" },
    { title: "必要な時にサポート", desc: "行き詰まったり、疲れたり、一日休んでしまったりしても、プランが軌道修正をサポートします。" }
  ],
  socialText: "すでに数百万人がチャレンジを開始しています",
  socialSub: "そして多くの人が着実に成果を上げています。",
  socialCta: "今すぐ開始",
  ratingsHeadline: "15,500件以上",
  ratingsSubline: "の5つ星評価",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Play Store",
  ratingsQuote: "最も効果的な減量アシスタント。",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Zero Carbs チャレンジ利用者のリアルな声",
  storiesSubheading: "私たちはこれらの結果を誇りに思っており、あなたの結果を見るのも楽しみにしています。",
  verifiedCustomer: "認証済みユーザー",
  choosePlanAria: "プランを選択",
  savingsText: "__AMOUNT__（__PERCENT__%）節約",
  trustSecureCheckout: "安全な決済",
  trustCancelAnytime: "いつでもキャンセル可能",
  trustInstantAccess: "即座にアクセス",
  footerLanguageLabel: "言語",
  secretGiftPill: "シークレットギフトをゲット！",
  secretGiftLead: "3ヶ月プランを選択した場合：",
  secretGiftTitle: "シークレットギフト",
  secretGiftBody: "Zero Carbs チャレンジチームは、あなたの食生活の改善をサポートし、特別なサプライズをご用意しました。",
  giftSectionTitle: "3ヶ月プランを購入してゲット：",
  giftSectionHighlight: "シークレットギフト",
  giftSectionWorth: "（50ドル相当）",
  giftSectionBody: "Zero Carbs チャレンジチームは、あなたの食生活の改善をサポートし、特別なサプライズをご用意しました。",
  guaranteePrefix: "適用される制限事項の詳細は、当社の",
  personalHeading: (name) => "__NAME__さん、自分のペースで確かな結果を".replace("__NAME__", String(name)),
  guaranteeTitle: "30日間返金保証",
  guaranteeBody: "リスクなしでZero Carbs チャレンジをお試しください。合わない場合は、30日以内に返金を申請できます。詳細は返金ポリシーをご確認ください。",
  guaranteeLinkLabel: "返金ポリシー",
  footer: "© 2026 Zero Carbs Challenge. 無断複写・転載を禁じます。",
  goalLabels: { "lose-weight":"体重を減らす", "heart-health":"心臓の健康を改善", "firm-toned":"体を引き締める", "lower-bio-age":"若々しく活力に満ちた感覚に" },
  sleepLabels: { "less-than-5":"低い", "<5":"低い", "5-6":"改善の余地あり", "7-8":"良い", "8-9":"良い", "9+":"さらに改善可能" },
  fitnessLabels: { sedentary:"低い", "lightly-active":"低い", light:"低い", moderate:"普通", intermediate:"普通", active:"高い", "very-active":"高い", advanced:"高い" },
  bmi: {
    Normal: { title: "良好なスタート地点", text: (bmi) => "あなたのBMIは__BMI__で、標準の範囲内です。順調です。あなたのニーズに合わせてプランを調整し、進捗の維持をサポートします。".replace("__BMI__", String(bmi)) },
    Underweight: { title: "良好なスタート地点", text: (bmi) => "あなたのBMIは__BMI__で、標準以下の範囲。筋肉量アップとバランスの取れた栄養に重点を置いたプランを作成します。".replace("__BMI__", String(bmi)) },
    Overweight: { title: "変化を起こす絶好のタイミング", text: (bmi) => "あなたのBMIは__BMI__。正しいルーチンで体の状態を改善できます。日常生活にフィットするプランで、一歩ずつガイドします。".replace("__BMI__", String(bmi)) },
    Obese: { title: "体をケアする絶好のタイミング", text: (bmi) => "あなたのBMIは__BMI__。適切なプランで、体の状態と動きを改善できます。日常生活に合う、簡単で小さなステップからガイドします。".replace("__BMI__", String(bmi)) }
  },
},
  ru: {
  plans: [
    { name: "План на 7 дней", desc: "USD 1.09 / день", badge: "Самый популярный — экономия более 50%" },
    { name: "План на 1 месяц", desc: "USD 0.61 / день", badge: null },
    { name: "План на 3 месяца", desc: "USD 0.31 / день", badge: "Самый выгодный" }
  ],
  pageTitle: "Ваш персонализированный план челленджа «Без углеводов» готов",
  pageSub: "Выберите план, который вам больше всего подходит.",
  stickyTimerLabel: "Ваша специальная скидка 50%+ зарезервирована на:",
  stickyMinutesLabel: "минут",
  stickySecondsLabel: "секунд",
  beforeLabel: "Сейчас",
  afterLabel: "Цель",
  bodyFatLabel: "Жир в теле",
  bodyFatHigh: "Высокий",
  bodyFatNormal: "Норма",
  bodyFatLow: "Низкий",
  fitnessLevelLabel: "Уровень подготовки",
  fitnessLevelBeginner: "Новичок",
  fitnessLevelIntermediate: "Средний",
  fitnessLevelAdvanced: "Продвинутый",
  discount: (v) => "со скидкой __V__".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ в день".replace("__V__", String(v)),
  moneyBackRow: "30-дневная гарантия возврата денег — попробуйте без риска. Если программа вам не подойдет, мы вернем деньги.",
  cta: "Получить мой план",
  consentPrefix: "Продолжая, вы соглашаетесь с нашими",
  terms: "Условиями использования",
  privacy: "Политикой конфиденциальности",
  refund: "Правилами возврата",
  consentAnd: "и",
  consentError: "Пожалуйста, примите условия, чтобы продолжить.",
  consentBody: (today, renew) => "Это подписка, которая продлевается автоматически. Сегодня с вас будет списано __TODAY__. После окончания периода плана ваша подписка будет продлена за __RENEW__, если вы ее не отмените. Вы можете отменить подписку в любое время, как минимум за 48 часов до продления, обратившись в службу поддержки по email:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Ваши результаты",
  primaryGoal: "ОСНОВНАЯ ЦЕЛЬ",
  fitnessLevel: "УРОВЕНЬ ПОДГОТОВКИ",
  sleepQuality: "КАЧЕСТВО СНА",
  fitnessAge: "ФИТНЕС-ВОЗРАСТ",
  fitnessAgeValue: (years) => "на __YEARS__ лет старше вашего реального возраста".replace("__YEARS__", String(years)),
  workoutTitle: "Ваш персонализированный план челленджа «Без углеводов»",
  workoutBadge: "РЕКОМЕНДУЕМАЯ ДЛИТЕЛЬНОСТЬ ТРЕНИРОВКИ",
  waterTitle: "Потребление воды",
  waterBadge: "РЕКОМЕНДУЕМАЯ ДНЕВНАЯ НОРМА ВОДЫ",
  readyHeading: "Ваш план с челленджем «Без углеводов» готов!",
  bulletTitle: "С челленджем «Без углеводов» вы сможете:",
  bullets: ["Обретите уверенность", "Повысьте уровень энергии", "Снизьте уровень стресса", "Поддерживайте свое тело со временем"],
  whatYouGet: "Что вы получите с челленджем «Без углеводов»",
  phoneMealTag: "Завтрак",
  phoneMealTitle: "Жареный лосось со стручковой фасолью",
  phoneMealMeta: "4.8 · 10 мин · 498 ккал",
  phoneIngredientsTab: "Ингредиенты",
  phoneNutritionTab: "Питательная ценность",
  phoneIngredient1: "Стручковая фасоль",
  phoneIngredient1Qty: "1 чашка",
  phoneIngredient2: "Лимон",
  phoneIngredient2Qty: "1 средний",
  phoneIngredient3: "Кунжут",
  phoneIngredient3Qty: "1 ст. л.",
  phoneIngredient4: "Оливковое масло",
  phoneIngredient4Qty: "3 1/2 ч. л.",
  features: [
    { title: "Персонализированный план", desc: "Ваш план строится вокруг вашего тела, вашей энергии и вашего образа жизни, а не по стандартному шаблону." },
    { title: "Простые ежедневные рекомендации", desc: "Вы всегда знаете, что делать сегодня, без лишних раздумий и планирования." },
    { title: "Адаптивное руководство", desc: "Ваш план корректируется по ходу дела — на основе вашего прогресса, энергии и дисциплины." },
    { title: "Поддержка, когда она вам нужна", desc: "Если вы чувствуете, что застряли, устали или пропустили день — ваш план поможет вам вернуться в строй." }
  ],
  socialText: "Миллионы людей уже начали свой путь",
  socialSub: "И многие увидели реальный прогресс со временем.",
  socialCta: "Начать сейчас",
  ratingsHeadline: "15,500+",
  ratingsSubline: "пятизвездочных оценок",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Google Play",
  ratingsQuote: "Самый эффективный помощник для похудения.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Реальные истории людей, использующих челлендж «Без углеводов»",
  storiesSubheading: "Мы гордимся этими результатами и с нетерпением ждем ваших.",
  verifiedCustomer: "Проверенный пользователь",
  choosePlanAria: "Выберите свой план",
  savingsText: "Вы экономите __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "Безопасная оплата",
  trustCancelAnytime: "Отмена в любое время",
  trustInstantAccess: "Мгновенный доступ",
  footerLanguageLabel: "Язык",
  secretGiftPill: "Получите секретный подарок!",
  secretGiftLead: "При выборе 3-месячного плана:",
  secretGiftTitle: "Секретный подарок",
  secretGiftBody: "Команда челленджа «Без углеводов» хочет поддержать вашу трансформацию отношений с едой и подготовила для вас секретный сюрприз.",
  giftSectionTitle: "Купите 3-месячный план и получите",
  giftSectionHighlight: "СЕКРЕТНЫЙ подарок",
  giftSectionWorth: " (стоимостью $50)",
  giftSectionBody: "Команда челленджа «Без углеводов» хочет поддержать вашу трансформацию отношений с едой и подготовила для вас секретный сюрприз.",
  guaranteePrefix: "Узнайте больше о действующих ограничениях в нашей",
  personalHeading: (name) => "__NAME__, создавайте реальные результаты в своем темпе".replace("__NAME__", String(name)),
  guaranteeTitle: "30-дневная гарантия возврата денег",
  guaranteeBody: "Попробуйте челлендж «Без углеводов» без риска. Если он вам не подойдет, вы можете запросить возврат средств в течение 30 дней. Пожалуйста, ознакомьтесь с нашими Правилами возврата для получения полной информации.",
  guaranteeLinkLabel: "политикой возврата денег",
  footer: "© 2026 челлендж «Без углеводов». Все права защищены.",
  goalLabels: { "lose-weight":"Сбросить вес", "heart-health":"Укрепить здоровье сердца", "firm-toned":"Подтянуть фигуру", "lower-bio-age":"Чувствовать себя моложе и энергичнее" },
  sleepLabels: { "less-than-5":"Плохо", "<5":"Плохо", "5-6":"Требует улучшения", "7-8":"Хорошо", "8-9":"Хорошо", "9+":"Могло бы быть лучше" },
  fitnessLabels: { sedentary:"Низкий", "lightly-active":"Низкий", light:"Низкий", moderate:"Средний", intermediate:"Средний", active:"Высокий", "very-active":"Высокий", advanced:"Высокий" },
  bmi: {
    Normal: { title: "Хорошая начальная точка", text: (bmi) => "Ваш ИМТ составляет __BMI__, что в пределах нормы. Вы на правильном пути. Ваш план будет адаптирован к вашим потребностям, чтобы помочь сохранить прогресс.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Хорошая начальная точка", text: (bmi) => "Ваш ИМТ составляет __BMI__, что ниже обычного диапазона. Ваш план будет сосредоточен на укреплении сил и сбалансированном питании.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "Хорошее время для перемен", text: (bmi) => "Ваш ИМТ составляет __BMI__. С правильным режимом вы сможете улучшить самочувствие. Мы будем вести вас шаг за шагом с планом, подходящим для вашей повседневной жизни.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Хорошее время позаботиться о своем теле", text: (bmi) => "Ваш ИМТ составляет __BMI__. С правильным планом вы сможете улучшить самочувствие и подвижность. Мы будем вести вас небольшими простыми шагами, подходящими для вашей жизни.".replace("__BMI__", String(bmi)) }
  },
},
  sk: {
  plans: [
    { name: "7-dňový plán", desc: "1,09 USD / deň", badge: "Najobľúbenejšie — ušetrite viac ako 50 %" },
    { name: "1-mesačný plán", desc: "0,61 USD / deň", badge: null },
    { name: "3-mesačný plán", desc: "0,31 USD / deň", badge: "Najlepšia ponuka" }
  ],
  pageTitle: "Váš personalizovaný plán výzvy bez sacharidov je pripravený",
  pageSub: "Vyberte si plán, ktorý vám najviac vyhovuje.",
  stickyTimerLabel: "Vaša špeciálna zľava 50%+ je rezervovaná na:",
  stickyMinutesLabel: "minút",
  stickySecondsLabel: "sekúnd",
  beforeLabel: "Teraz",
  afterLabel: "Cieľ",
  bodyFatLabel: "Telesný tuk",
  bodyFatHigh: "Vysoký",
  bodyFatNormal: "Normálny",
  bodyFatLow: "Nízky",
  fitnessLevelLabel: "Úroveň kondície",
  fitnessLevelBeginner: "Začiatočník",
  fitnessLevelIntermediate: "Pokročilý",
  fitnessLevelAdvanced: "Expert",
  discount: (v) => "so zľavou __V__".replace("__V__", String(v)),
  perDay: (v) => "≈ __V__ za deň".replace("__V__", String(v)),
  moneyBackRow: "30-dňová záruka vrátenia peňazí — vyskúšajte bez rizika. Ak vám plán nebude vyhovovať, vrátime vám peniaze.",
  cta: "Získať môj plán",
  consentPrefix: "Pokračovaním súhlasíte s našimi",
  terms: "Zmluvnými podmienkami",
  privacy: "Zásadami ochrany osobných údajov",
  refund: "Zásadami vrátenia platby",
  consentAnd: "a",
  consentError: "Ak chcete pokračovať, prijmite zmluvné podmienky.",
  consentBody: (today, renew) => "Toto je predplatné, ktoré sa automaticky obnovuje. Dnes vám bude účtovaná suma __TODAY__. Po skončení obdobia sa váš plán obnoví za cenu __RENEW__, ak ho nezrušíte. Plán môžete zrušiť kedykoľvek, najmenej 48 hodín pred obnovením, kontaktovaním podpory e-mailom:".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "Vaše výsledky",
  primaryGoal: "HLAVNÝ CIEĽ",
  fitnessLevel: "ÚROVEŇ KONDÍCIE",
  sleepQuality: "KVALITA SPÁNKU",
  fitnessAge: "KONDICIÁLNY VEK",
  fitnessAgeValue: (years) => "o __YEARS__ rokov vyšší ako váš skutočný vek".replace("__YEARS__", String(years)),
  workoutTitle: "Váš personalizovaný plán výzvy bez sacharidov",
  workoutBadge: "ODPORÚČANÁ DĹŽKA TRÉNINGU",
  waterTitle: "Príjem vody",
  waterBadge: "ODPORÚČANÝ DENNÝ PRÍJEM VODY",
  readyHeading: "Váš plán s výzvou bez sacharidov je pripravený!",
  bulletTitle: "S výzvou bez sacharidov môžete:",
  bullets: ["Získajte sebavedomie", "Zvýšte svoju energiu", "Znížte stres", "Podporte svoje telo dlhodobo"],
  whatYouGet: "Čo získate s výzvou bez sacharidov",
  phoneMealTag: "Raňajky",
  phoneMealTitle: "Pečený losos so zelenou fazuľkou",
  phoneMealMeta: "4.8 · 10 min · 498 kcal",
  phoneIngredientsTab: "Ingrediencie",
  phoneNutritionTab: "Nutričné hodnoty",
  phoneIngredient1: "Zelená fazuľka",
  phoneIngredient1Qty: "1 šálka",
  phoneIngredient2: "Citrón",
  phoneIngredient2Qty: "1 stredný",
  phoneIngredient3: "Sezamové semienka",
  phoneIngredient3Qty: "1 PL",
  phoneIngredient4: "Olivový olej",
  phoneIngredient4Qty: "3 1/2 ČL",
  features: [
    { title: "Personalizovaný plán", desc: "Váš plán je zostavený na mieru vášmu telu, energii a každodennému životu – nie je to žiadny generický postup." },
    { title: "Jednoduché denné pokyny", desc: "Vždy viete, čo máte v daný deň urobiť, bez zbytočného premýšľania či plánovania." },
    { title: "Adaptívne vedenie", desc: "Váš plán sa priebežne prispôsobuje – na základe vášho pokroku, energie a dôslednosti." },
    { title: "Podpora, keď ju potrebujete", desc: "Ak sa cítite zaseknutí, unavení alebo vynecháte deň – váš plán vám pomôže vrátiť sa späť na cestu." }
  ],
  socialText: "Milióny ľudí už začali svoju cestu",
  socialSub: "Mnohí zaznamenali reálny pokrok v priebehu času.",
  socialCta: "Začať teraz",
  ratingsHeadline: "15 500+",
  ratingsSubline: "5-hviezdičkových hodnotení",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Google Play",
  ratingsQuote: "Najúčinnejší pomocník pri chudnutí.",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Skutočné príbehy ľudí, ktorí využívajú výzvu bez sacharidov",
  storiesSubheading: "Sme hrdí na tieto výsledky a tešíme sa na tie vaše.",
  verifiedCustomer: "Overený zákazník",
  choosePlanAria: "Vyberte si svoj plán",
  savingsText: "Ušetríte __AMOUNT__ (__PERCENT__ %)",
  trustSecureCheckout: "Bezpečná platba",
  trustCancelAnytime: "Zrušiť kedykoľvek",
  trustInstantAccess: "Okamžitý prístup",
  footerLanguageLabel: "Jazyk",
  secretGiftPill: "Získajte tajný darček!",
  secretGiftLead: "Ak si vyberiete 3-mesačný plán:",
  secretGiftTitle: "Tajný darček",
  secretGiftBody: "Tím výzvy bez sacharidov chce podporiť vašu zmenu a pripravil pre vás tajné prekvapenie.",
  giftSectionTitle: "Kúpte si 3-mesačný plán a získajte",
  giftSectionHighlight: "TAJNÝ darček",
  giftSectionWorth: " (v hodnote 50 USD)",
  giftSectionBody: "Tím výzvy bez sacharidov chce podporiť vašu zmenu a pripravil pre vás tajné prekvapenie.",
  guaranteePrefix: "Viac o platných obmedzeniach v našich",
  personalHeading: (name) => "__NAME__, dosiahnite skutočné výsledky vlastným tempom".replace("__NAME__", String(name)),
  guaranteeTitle: "30-dňová záruka vrátenia peňazí",
  guaranteeBody: "Vyskúšajte výzvu bez sacharidov bez rizika. Ak vám nebude vyhovovať, môžete požiadať o vrátenie peňazí do 30 dní. Podrobnosti nájdete v našich zásadách vrátenia platby.",
  guaranteeLinkLabel: "zásadách vrátenia peňazí",
  footer: "© 2026 výzva bez sacharidov. Všetky práva vyhradené.",
  goalLabels: { "lose-weight":"Schudnúť", "heart-health":"Zlepšiť zdravie srdca", "firm-toned":"Spevniť postavu", "lower-bio-age":"Cítiť sa mladšie a energickejšie" },
  sleepLabels: { "less-than-5":"Slabá", "<5":"Slabá", "5-6":"Vyžaduje zlepšenie", "7-8":"Dobrá", "8-9":"Dobrá", "9+":"Mohla by byť lepšia" },
  fitnessLabels: { sedentary:"Nízka", "lightly-active":"Nízka", light:"Nízka", moderate:"Stredná", intermediate:"Stredná", active:"Vysoká", "very-active":"Vysoká", advanced:"Vysoká" },
  bmi: {
    Normal: { title: "Dobrý počiatočný bod", text: (bmi) => "Vaše BMI je __BMI__, čo je v normálnom rozmedzí. Ste na správnej ceste. Váš plán bude prispôsobený vašim potrebám, aby vám pomohol udržať progres.".replace("__BMI__", String(bmi)) },
    Underweight: { title: "Dobrý počiatočný bod", text: (bmi) => "Vaše BMI je __BMI__, čo je pod normálnym rozmedzím. Váš plán sa zameria na budovanie sily a vyváženú výživu.".replace("__BMI__", String(bmi)) },
    Overweight: { title: "Vhodný čas na zmenu", text: (bmi) => "Vaše BMI je __BMI__. So správnou rutinou môžete zlepšiť to, ako sa vaše telo cíti. Povedieme vás krok za krokom s plánom, ktorý vyhovuje vášmu životu.".replace("__BMI__", String(bmi)) },
    Obese: { title: "Vhodný čas postarať sa o svoje telo", text: (bmi) => "Vaše BMI je __BMI__. So správnym plánom môžete zlepšiť svoje pocity a pohyb. Povedieme vás malými, jednoduchými krokmi prispôsobenými vášmu životu.".replace("__BMI__", String(bmi)) }
  },
},
  tw: {
  plans: [
    { name: "7 天計畫", desc: "每天 USD 1.09", badge: "最受歡迎 — 節省超過 50%" },
    { name: "1 個月計畫", desc: "每天 USD 0.61", badge: null },
    { name: "3 個月計畫", desc: "每天 USD 0.31", badge: "最划算" }
  ],
  pageTitle: "您的個人化 Zero Carbs 挑戰計畫已準備就緒",
  pageSub: "挑選最適合您的計畫。",
  stickyTimerLabel: "您的 50% 以上特別折扣保留至：",
  stickyMinutesLabel: "分鐘",
  stickySecondsLabel: "秒",
  beforeLabel: "現在",
  afterLabel: "目標",
  bodyFatLabel: "體脂肪",
  bodyFatHigh: "高",
  bodyFatNormal: "正常",
  bodyFatLow: "低",
  fitnessLevelLabel: "體能等級",
  fitnessLevelBeginner: "初學者",
  fitnessLevelIntermediate: "中級者",
  fitnessLevelAdvanced: "進階者",
  discount: (v) => "包含 __V__ 折扣".replace("__V__", String(v)),
  perDay: (v) => "每天約 __V__".replace("__V__", String(v)),
  moneyBackRow: "30 天退款保證 — 無風險試用。如果不適合您，您可以退款。",
  cta: "取得我的計畫",
  consentPrefix: "繼續即表示您同意我們的",
  terms: "使用條款",
  privacy: "隱私權政策",
  refund: "退款政策",
  consentAnd: "以及",
  consentError: "請接受條款以繼續。",
  consentBody: (today, renew) => "這是一項自動續訂的訂閱。您今天將被收取 __TODAY__。計畫期結束後，您的計畫將以 __RENEW__ 續訂，除非您取消。您可以在續訂前至少 48 小時隨時聯絡支援電子郵件來取消：".replace("__TODAY__", String(today)).replace("__RENEW__", String(renew)),
  yourResults: "您的結果",
  primaryGoal: "主要目標",
  fitnessLevel: "體能等級",
  sleepQuality: "睡眠品質",
  fitnessAge: "體能年齡",
  fitnessAgeValue: (years) => "比您的實際年齡大 __YEARS__ 歲".replace("__YEARS__", String(years)),
  workoutTitle: "個人化 Zero Carbs 挑戰計畫",
  workoutBadge: "建議運動時長",
  waterTitle: "水分攝取",
  waterBadge: "建議每日水分攝取量",
  readyHeading: "您的 Zero Carbs 挑戰計畫已備妥！",
  bulletTitle: "透過 Zero Carbs 挑戰，您可以：",
  bullets: ["建立自信", "提升精力", "減輕壓力", "隨時間推移支援您的身體健康"],
  whatYouGet: "透過 Zero Carbs 挑戰您將獲得",
  phoneMealTag: "早餐",
  phoneMealTitle: "香煎鮭魚佐四季豆",
  phoneMealMeta: "4.8 · 10 分鐘 · 498 kcal",
  phoneIngredientsTab: "食材",
  phoneNutritionTab: "營養成分",
  phoneIngredient1: "四季豆",
  phoneIngredient1Qty: "1 杯",
  phoneIngredient2: "檸檬",
  phoneIngredient2Qty: "1 個 (中型)",
  phoneIngredient3: "芝麻",
  phoneIngredient3Qty: "1 大匙",
  phoneIngredient4: "橄欖油",
  phoneIngredient4Qty: "3 1/2 小匙",
  features: [
    { title: "個人化計畫", desc: "您的計畫是圍繞您的體質、精力和日常生活打造的 — 而不是通用的例行公事。" },
    { title: "簡單的每日指引", desc: "您始終知道今天該做什麼，無需思考或計畫。" },
    { title: "適應性指導", desc: "您的計畫會隨時調整 — 根據您的進度、精力和一致性。" },
    { title: "需要時提供支援", desc: "如果您感到停滯、疲倦或錯過了一天 — 您的計畫會幫助您回到正軌。" }
  ],
  socialText: "已有數百萬人開始了他們的旅程",
  socialSub: "許多人隨著時間看到了真正的進步。",
  socialCta: "立即開始",
  ratingsHeadline: "15,500+",
  ratingsSubline: "的 5 星好評",
  ratingsAppStore: "App Store",
  ratingsPlayStore: "Play Store",
  ratingsQuote: "最有效的體重減輕助手。",
  ratingsQuoteSource: "Honest Brand Reviews",
  storiesHeading: "Zero Carbs 挑戰使用者的真實故事",
  storiesSubheading: "我們為這些結果感到自豪，並迫不及待想看到您的成果。",
  verifiedCustomer: "驗證客戶",
  choosePlanAria: "選擇您的計畫",
  savingsText: "您節省了 __AMOUNT__ (__PERCENT__%)",
  trustSecureCheckout: "安全結帳",
  trustCancelAnytime: "隨時取消",
  trustInstantAccess: "立即存取",
  footerLanguageLabel: "語言",
  secretGiftPill: "取得神秘禮物！",
  secretGiftLead: "如果您選擇 3 個月計畫：",
  secretGiftTitle: "神秘禮物",
  secretGiftBody: "Zero Carbs 挑戰團隊希望能支援您與食物關係的轉變，並為您準備了神秘驚喜。",
  giftSectionTitle: "購買 3 個月計畫即可獲得",
  giftSectionHighlight: "神秘禮物",
  giftSectionWorth: " (價值 $50)",
  giftSectionBody: "Zero Carbs 挑戰團隊希望能支援您與食物關係的轉變，並為您準備了神秘驚喜。",
  guaranteePrefix: "在我們的內容中尋找更多關於適用限制的資訊",
  personalHeading: (name) => "__NAME__，按您的節奏建立真正的結果".replace("__NAME__", String(name)),
  guaranteeTitle: "30 天退款保證",
  guaranteeBody: "無風險試用 Zero Carbs 挑戰。如果不適合您，您可以在 30 天內申請退款。請查看我們的退款政策了解完整細節。",
  guaranteeLinkLabel: "退款政策",
  footer: "© 2026 Zero Carbs Challenge. 保留所有權利。",
  goalLabels: { "lose-weight":"減輕體重", "heart-health":"改善心臟健康", "firm-toned":"塑造更緊緻的體態", "lower-bio-age":"感覺更年輕且充滿活力" },
  sleepLabels: { "less-than-5":"較差", "<5":"較差", "5-6":"有待改善", "7-8":"良好", "8-9":"良好", "9+":"可以更好" },
  fitnessLabels: { sedentary:"低", "lightly-active":"低", light:"低", moderate:"中", intermediate:"中", active:"高", "very-active":"高", advanced:"高" },
  bmi: {
    Normal: { title: "良好的起點", text: (bmi) => "您的 BMI 為 __BMI__，處於正常範圍。您正步入正軌。您的計畫將進行調整以符合您的需求，並幫助您保持進度。".replace("__BMI__", String(bmi)) },
    Underweight: { title: "良好的起點", text: (bmi) => "您的 BMI 為 __BMI__，低於通常範圍。您的計畫將側重於鍛鍊體力與均衡營養。".replace("__BMI__", String(bmi)) },
    Overweight: { title: "做出改變的好時機", text: (bmi) => "您的 BMI 為 __BMI__。透過正確的日常習慣，您可以改善身體的感覺。我們將透過適合您日常生活的計畫逐步引導您。".replace("__BMI__", String(bmi)) },
    Obese: { title: "照顧身體的好時機", text: (bmi) => "您的 BMI 為 __BMI__。透過正確的計畫，您可以改善身體的感覺與活動。我們將以貼合您日常生活的簡單小步驟來引導您。".replace("__BMI__", String(bmi)) }
  },
}
}
